#ifndef GLOBALS_H
#define GLOBALS_H

#include <stdio.h>
#include <syslog.h>
#include <string.h>

#include <stdint.h>

#include "App_queue.h"
#include "cvector.h"

#pragma pack(1) /* 按字节对齐 */

// 全网卫星总数
#define SAT_TOTALNUM 2
// 全网总用户数
#define UE_TOTALNUM 4000
// 单个卫星用户容量
#define UE_PERMITNUM 1500
// 每个卫星上/下行波束总数
#define BEAM_TOTALNUM 8
// 虚波位总数
#define WAVE_TOTALNUM 600
// 单个波束需要轮询的虚波位总数
#define WAVE_NUM (WAVE_TOTALNUM / (BEAM_TOTALNUM / 2))
// 控制信道时隙数
#define CSLOT_TOTALNUM 1
// 业务信道时隙数
#define SSLOT_TOTALNUM 3
// 每个时隙的RB数量
#define RB_TOTALNUM 250
// 单个卫星用户容量
#define MAX_USERS 1500
// 单个用户上/下行业务面视频/语音业务（驻留业务）可占用最大RB数量
#define SCH_RB_FREQ_POINT_ARRAY_SIZE 20

// 单个用户上/下行控制面可占用最大RB数量
#define CCH_RB_FREQ_POINT_ARRAY_SIZE 25
// 单个虚波位可接入的UE数量阈值
#define WAVE_MAX_USERS 200
// 当前允许资源池被占用的RB数量阈值
#define MAX_OCCUPY_RB 650
// 单个基带单元可接入的用户上限
#define BBU_UE_MAXNUM 250
// UE发送在线状态报告的周期
#define UE_ONLINE_REPORT_PERIOD 2.0
// 卫星检测在线状态报告的周期
#define ONLINE_DETECT_PERIOD (3 * UE_ONLINE_REPORT_PERIOD)
// 业务信道RB总数
#define SCH_RB_NUM 750
// 用户优先级数目
#define UE_LEVEL_NUM 3
// 每个虚波位上的最大接入用户数
#define PER_WAVE_MAX_NUM 10
// 单个用户每次可以下发的最大业务信道数据总量，包括MAC帧头
#define PER_UE_MAX_DL_VOLUME (1024 * 4)
// MAC帧头大小 6 + 6 + 2 + 2
#define MAC_FRAME_LENGTH 16

#define CCH_DATA_LENGTH 87

#define PCIE_WRITE1_SFFSET 0
#define PCIE_WRITE2_SFFSET 6144
#define PCIE_READ_OFFSET 8192

// #define filename(x) strrchr(x,'/')?strrchr(x,'/')+1:x
// #define LOG(format,args...) (printf("[%s]-[%d]:" format "\r\n",filename(__FILE__),__LINE__,##args))

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef struct
{
    u8 value[6];
} u48;

typedef long unsigned int u64;
// [NEW] 随机接入请求队列（解耦仿真生成与实际处理）
extern App_queue Queue_RACH_Req;

// [NEW] MAC 层全局互斥锁（保护 wave_ueser_mapPtrArray 等共享资源）
extern pthread_mutex_t Global_MAC_Lock;
extern u48 own_address;     // 本UE的MAC地址
extern u16 poll_wave_index; // 虚波位轮询
extern u48 get_sat_MAC;
extern u32 get_ue_rnti;
extern u48 get_ue_addr;
extern int is_RandomAccess_success;
extern long minimumTimeAdvance_to_PHY;
extern long slot_division_period; // 时帧维护的周期

extern u16 BBU_index;

extern App_queue mac_ce_pdu[2]; // 逻辑信道组bsr的缓存值
extern App_queue Queue_UL_DataSum;
extern App_queue Queue_DL_DataSum;
extern App_queue Queue_UDP_recv_sat_rrc;
extern App_queue Queue_UDP_recv_sat_rlc;
extern App_queue Queue_UDP_recv_ue_mac_u;

extern App_queue Queue_UDP_SCHSend;
extern App_queue Queue_UDP_CCHSend;
extern App_queue Queue_recv_divdata;

extern App_queue Queue_ULCCH_idleRB_fifo_000;
extern App_queue Queue_ULCCH_idleRB_fifo_001;
extern App_queue Queue_ULCCH_idleRB_fifo_002;
extern App_queue Queue_ULCCH_idleRB_fifo_003;
extern App_queue Queue_ULCCH_idleRB_fifo_004;
extern App_queue Queue_ULCCH_idleRB_fifo_005;
extern App_queue Queue_ULCCH_idleRB_fifo_006;
extern App_queue Queue_ULCCH_idleRB_fifo_007;
extern App_queue Queue_ULCCH_idleRB_fifo_008;
extern App_queue Queue_ULCCH_idleRB_fifo_009;
extern App_queue Queue_ULCCH_idleRB_fifo_010;
extern App_queue Queue_ULCCH_idleRB_fifo_011;
extern App_queue Queue_ULCCH_idleRB_fifo_012;
extern App_queue Queue_ULCCH_idleRB_fifo_013;
extern App_queue Queue_ULCCH_idleRB_fifo_014;
extern App_queue Queue_ULCCH_idleRB_fifo_015;
extern App_queue Queue_ULCCH_idleRB_fifo_016;
extern App_queue Queue_ULCCH_idleRB_fifo_017;
extern App_queue Queue_ULCCH_idleRB_fifo_018;
extern App_queue Queue_ULCCH_idleRB_fifo_019;
extern App_queue Queue_ULCCH_idleRB_fifo_020;
extern App_queue Queue_ULCCH_idleRB_fifo_021;
extern App_queue Queue_ULCCH_idleRB_fifo_022;
extern App_queue Queue_ULCCH_idleRB_fifo_023;
extern App_queue Queue_ULCCH_idleRB_fifo_024;
extern App_queue Queue_ULCCH_idleRB_fifo_025;
extern App_queue Queue_ULCCH_idleRB_fifo_026;
extern App_queue Queue_ULCCH_idleRB_fifo_027;
extern App_queue Queue_ULCCH_idleRB_fifo_028;
extern App_queue Queue_ULCCH_idleRB_fifo_029;
extern App_queue Queue_ULCCH_idleRB_fifo_030;
extern App_queue Queue_ULCCH_idleRB_fifo_031;
extern App_queue Queue_ULCCH_idleRB_fifo_032;
extern App_queue Queue_ULCCH_idleRB_fifo_033;
extern App_queue Queue_ULCCH_idleRB_fifo_034;
extern App_queue Queue_ULCCH_idleRB_fifo_035;
extern App_queue Queue_ULCCH_idleRB_fifo_036;
extern App_queue Queue_ULCCH_idleRB_fifo_037;
extern App_queue Queue_ULCCH_idleRB_fifo_038;
extern App_queue Queue_ULCCH_idleRB_fifo_039;
extern App_queue Queue_ULCCH_idleRB_fifo_040;
extern App_queue Queue_ULCCH_idleRB_fifo_041;
extern App_queue Queue_ULCCH_idleRB_fifo_042;
extern App_queue Queue_ULCCH_idleRB_fifo_043;
extern App_queue Queue_ULCCH_idleRB_fifo_044;
extern App_queue Queue_ULCCH_idleRB_fifo_045;
extern App_queue Queue_ULCCH_idleRB_fifo_046;
extern App_queue Queue_ULCCH_idleRB_fifo_047;
extern App_queue Queue_ULCCH_idleRB_fifo_048;
extern App_queue Queue_ULCCH_idleRB_fifo_049;
extern App_queue Queue_ULCCH_idleRB_fifo_050;
extern App_queue Queue_ULCCH_idleRB_fifo_051;
extern App_queue Queue_ULCCH_idleRB_fifo_052;
extern App_queue Queue_ULCCH_idleRB_fifo_053;
extern App_queue Queue_ULCCH_idleRB_fifo_054;
extern App_queue Queue_ULCCH_idleRB_fifo_055;
extern App_queue Queue_ULCCH_idleRB_fifo_056;
extern App_queue Queue_ULCCH_idleRB_fifo_057;
extern App_queue Queue_ULCCH_idleRB_fifo_058;
extern App_queue Queue_ULCCH_idleRB_fifo_059;
extern App_queue Queue_ULCCH_idleRB_fifo_060;
extern App_queue Queue_ULCCH_idleRB_fifo_061;
extern App_queue Queue_ULCCH_idleRB_fifo_062;
extern App_queue Queue_ULCCH_idleRB_fifo_063;
extern App_queue Queue_ULCCH_idleRB_fifo_064;
extern App_queue Queue_ULCCH_idleRB_fifo_065;
extern App_queue Queue_ULCCH_idleRB_fifo_066;
extern App_queue Queue_ULCCH_idleRB_fifo_067;
extern App_queue Queue_ULCCH_idleRB_fifo_068;
extern App_queue Queue_ULCCH_idleRB_fifo_069;
extern App_queue Queue_ULCCH_idleRB_fifo_070;
extern App_queue Queue_ULCCH_idleRB_fifo_071;
extern App_queue Queue_ULCCH_idleRB_fifo_072;
extern App_queue Queue_ULCCH_idleRB_fifo_073;
extern App_queue Queue_ULCCH_idleRB_fifo_074;
extern App_queue Queue_ULCCH_idleRB_fifo_075;
extern App_queue Queue_ULCCH_idleRB_fifo_076;
extern App_queue Queue_ULCCH_idleRB_fifo_077;
extern App_queue Queue_ULCCH_idleRB_fifo_078;
extern App_queue Queue_ULCCH_idleRB_fifo_079;
extern App_queue Queue_ULCCH_idleRB_fifo_080;
extern App_queue Queue_ULCCH_idleRB_fifo_081;
extern App_queue Queue_ULCCH_idleRB_fifo_082;
extern App_queue Queue_ULCCH_idleRB_fifo_083;
extern App_queue Queue_ULCCH_idleRB_fifo_084;
extern App_queue Queue_ULCCH_idleRB_fifo_085;
extern App_queue Queue_ULCCH_idleRB_fifo_086;
extern App_queue Queue_ULCCH_idleRB_fifo_087;
extern App_queue Queue_ULCCH_idleRB_fifo_088;
extern App_queue Queue_ULCCH_idleRB_fifo_089;
extern App_queue Queue_ULCCH_idleRB_fifo_090;
extern App_queue Queue_ULCCH_idleRB_fifo_091;
extern App_queue Queue_ULCCH_idleRB_fifo_092;
extern App_queue Queue_ULCCH_idleRB_fifo_093;
extern App_queue Queue_ULCCH_idleRB_fifo_094;
extern App_queue Queue_ULCCH_idleRB_fifo_095;
extern App_queue Queue_ULCCH_idleRB_fifo_096;
extern App_queue Queue_ULCCH_idleRB_fifo_097;
extern App_queue Queue_ULCCH_idleRB_fifo_098;
extern App_queue Queue_ULCCH_idleRB_fifo_099;
extern App_queue Queue_ULCCH_idleRB_fifo_100;
extern App_queue Queue_ULCCH_idleRB_fifo_101;
extern App_queue Queue_ULCCH_idleRB_fifo_102;
extern App_queue Queue_ULCCH_idleRB_fifo_103;
extern App_queue Queue_ULCCH_idleRB_fifo_104;
extern App_queue Queue_ULCCH_idleRB_fifo_105;
extern App_queue Queue_ULCCH_idleRB_fifo_106;
extern App_queue Queue_ULCCH_idleRB_fifo_107;
extern App_queue Queue_ULCCH_idleRB_fifo_108;
extern App_queue Queue_ULCCH_idleRB_fifo_109;
extern App_queue Queue_ULCCH_idleRB_fifo_110;
extern App_queue Queue_ULCCH_idleRB_fifo_111;
extern App_queue Queue_ULCCH_idleRB_fifo_112;
extern App_queue Queue_ULCCH_idleRB_fifo_113;
extern App_queue Queue_ULCCH_idleRB_fifo_114;
extern App_queue Queue_ULCCH_idleRB_fifo_115;
extern App_queue Queue_ULCCH_idleRB_fifo_116;
extern App_queue Queue_ULCCH_idleRB_fifo_117;
extern App_queue Queue_ULCCH_idleRB_fifo_118;
extern App_queue Queue_ULCCH_idleRB_fifo_119;
extern App_queue Queue_ULCCH_idleRB_fifo_120;
extern App_queue Queue_ULCCH_idleRB_fifo_121;
extern App_queue Queue_ULCCH_idleRB_fifo_122;
extern App_queue Queue_ULCCH_idleRB_fifo_123;
extern App_queue Queue_ULCCH_idleRB_fifo_124;
extern App_queue Queue_ULCCH_idleRB_fifo_125;
extern App_queue Queue_ULCCH_idleRB_fifo_126;
extern App_queue Queue_ULCCH_idleRB_fifo_127;
extern App_queue Queue_ULCCH_idleRB_fifo_128;
extern App_queue Queue_ULCCH_idleRB_fifo_129;
extern App_queue Queue_ULCCH_idleRB_fifo_130;
extern App_queue Queue_ULCCH_idleRB_fifo_131;
extern App_queue Queue_ULCCH_idleRB_fifo_132;
extern App_queue Queue_ULCCH_idleRB_fifo_133;
extern App_queue Queue_ULCCH_idleRB_fifo_134;
extern App_queue Queue_ULCCH_idleRB_fifo_135;
extern App_queue Queue_ULCCH_idleRB_fifo_136;
extern App_queue Queue_ULCCH_idleRB_fifo_137;
extern App_queue Queue_ULCCH_idleRB_fifo_138;
extern App_queue Queue_ULCCH_idleRB_fifo_139;
extern App_queue Queue_ULCCH_idleRB_fifo_140;
extern App_queue Queue_ULCCH_idleRB_fifo_141;
extern App_queue Queue_ULCCH_idleRB_fifo_142;
extern App_queue Queue_ULCCH_idleRB_fifo_143;
extern App_queue Queue_ULCCH_idleRB_fifo_144;
extern App_queue Queue_ULCCH_idleRB_fifo_145;
extern App_queue Queue_ULCCH_idleRB_fifo_146;
extern App_queue Queue_ULCCH_idleRB_fifo_147;
extern App_queue Queue_ULCCH_idleRB_fifo_148;
extern App_queue Queue_ULCCH_idleRB_fifo_149;

extern App_queue Queue_DLCCH_idleRB_fifo_000;
extern App_queue Queue_DLCCH_idleRB_fifo_001;
extern App_queue Queue_DLCCH_idleRB_fifo_002;
extern App_queue Queue_DLCCH_idleRB_fifo_003;
extern App_queue Queue_DLCCH_idleRB_fifo_004;
extern App_queue Queue_DLCCH_idleRB_fifo_005;
extern App_queue Queue_DLCCH_idleRB_fifo_006;
extern App_queue Queue_DLCCH_idleRB_fifo_007;
extern App_queue Queue_DLCCH_idleRB_fifo_008;
extern App_queue Queue_DLCCH_idleRB_fifo_009;
extern App_queue Queue_DLCCH_idleRB_fifo_010;
extern App_queue Queue_DLCCH_idleRB_fifo_011;
extern App_queue Queue_DLCCH_idleRB_fifo_012;
extern App_queue Queue_DLCCH_idleRB_fifo_013;
extern App_queue Queue_DLCCH_idleRB_fifo_014;
extern App_queue Queue_DLCCH_idleRB_fifo_015;
extern App_queue Queue_DLCCH_idleRB_fifo_016;
extern App_queue Queue_DLCCH_idleRB_fifo_017;
extern App_queue Queue_DLCCH_idleRB_fifo_018;
extern App_queue Queue_DLCCH_idleRB_fifo_019;
extern App_queue Queue_DLCCH_idleRB_fifo_020;
extern App_queue Queue_DLCCH_idleRB_fifo_021;
extern App_queue Queue_DLCCH_idleRB_fifo_022;
extern App_queue Queue_DLCCH_idleRB_fifo_023;
extern App_queue Queue_DLCCH_idleRB_fifo_024;
extern App_queue Queue_DLCCH_idleRB_fifo_025;
extern App_queue Queue_DLCCH_idleRB_fifo_026;
extern App_queue Queue_DLCCH_idleRB_fifo_027;
extern App_queue Queue_DLCCH_idleRB_fifo_028;
extern App_queue Queue_DLCCH_idleRB_fifo_029;
extern App_queue Queue_DLCCH_idleRB_fifo_030;
extern App_queue Queue_DLCCH_idleRB_fifo_031;
extern App_queue Queue_DLCCH_idleRB_fifo_032;
extern App_queue Queue_DLCCH_idleRB_fifo_033;
extern App_queue Queue_DLCCH_idleRB_fifo_034;
extern App_queue Queue_DLCCH_idleRB_fifo_035;
extern App_queue Queue_DLCCH_idleRB_fifo_036;
extern App_queue Queue_DLCCH_idleRB_fifo_037;
extern App_queue Queue_DLCCH_idleRB_fifo_038;
extern App_queue Queue_DLCCH_idleRB_fifo_039;
extern App_queue Queue_DLCCH_idleRB_fifo_040;
extern App_queue Queue_DLCCH_idleRB_fifo_041;
extern App_queue Queue_DLCCH_idleRB_fifo_042;
extern App_queue Queue_DLCCH_idleRB_fifo_043;
extern App_queue Queue_DLCCH_idleRB_fifo_044;
extern App_queue Queue_DLCCH_idleRB_fifo_045;
extern App_queue Queue_DLCCH_idleRB_fifo_046;
extern App_queue Queue_DLCCH_idleRB_fifo_047;
extern App_queue Queue_DLCCH_idleRB_fifo_048;
extern App_queue Queue_DLCCH_idleRB_fifo_049;
extern App_queue Queue_DLCCH_idleRB_fifo_050;
extern App_queue Queue_DLCCH_idleRB_fifo_051;
extern App_queue Queue_DLCCH_idleRB_fifo_052;
extern App_queue Queue_DLCCH_idleRB_fifo_053;
extern App_queue Queue_DLCCH_idleRB_fifo_054;
extern App_queue Queue_DLCCH_idleRB_fifo_055;
extern App_queue Queue_DLCCH_idleRB_fifo_056;
extern App_queue Queue_DLCCH_idleRB_fifo_057;
extern App_queue Queue_DLCCH_idleRB_fifo_058;
extern App_queue Queue_DLCCH_idleRB_fifo_059;
extern App_queue Queue_DLCCH_idleRB_fifo_060;
extern App_queue Queue_DLCCH_idleRB_fifo_061;
extern App_queue Queue_DLCCH_idleRB_fifo_062;
extern App_queue Queue_DLCCH_idleRB_fifo_063;
extern App_queue Queue_DLCCH_idleRB_fifo_064;
extern App_queue Queue_DLCCH_idleRB_fifo_065;
extern App_queue Queue_DLCCH_idleRB_fifo_066;
extern App_queue Queue_DLCCH_idleRB_fifo_067;
extern App_queue Queue_DLCCH_idleRB_fifo_068;
extern App_queue Queue_DLCCH_idleRB_fifo_069;
extern App_queue Queue_DLCCH_idleRB_fifo_070;
extern App_queue Queue_DLCCH_idleRB_fifo_071;
extern App_queue Queue_DLCCH_idleRB_fifo_072;
extern App_queue Queue_DLCCH_idleRB_fifo_073;
extern App_queue Queue_DLCCH_idleRB_fifo_074;
extern App_queue Queue_DLCCH_idleRB_fifo_075;
extern App_queue Queue_DLCCH_idleRB_fifo_076;
extern App_queue Queue_DLCCH_idleRB_fifo_077;
extern App_queue Queue_DLCCH_idleRB_fifo_078;
extern App_queue Queue_DLCCH_idleRB_fifo_079;
extern App_queue Queue_DLCCH_idleRB_fifo_080;
extern App_queue Queue_DLCCH_idleRB_fifo_081;
extern App_queue Queue_DLCCH_idleRB_fifo_082;
extern App_queue Queue_DLCCH_idleRB_fifo_083;
extern App_queue Queue_DLCCH_idleRB_fifo_084;
extern App_queue Queue_DLCCH_idleRB_fifo_085;
extern App_queue Queue_DLCCH_idleRB_fifo_086;
extern App_queue Queue_DLCCH_idleRB_fifo_087;
extern App_queue Queue_DLCCH_idleRB_fifo_088;
extern App_queue Queue_DLCCH_idleRB_fifo_089;
extern App_queue Queue_DLCCH_idleRB_fifo_090;
extern App_queue Queue_DLCCH_idleRB_fifo_091;
extern App_queue Queue_DLCCH_idleRB_fifo_092;
extern App_queue Queue_DLCCH_idleRB_fifo_093;
extern App_queue Queue_DLCCH_idleRB_fifo_094;
extern App_queue Queue_DLCCH_idleRB_fifo_095;
extern App_queue Queue_DLCCH_idleRB_fifo_096;
extern App_queue Queue_DLCCH_idleRB_fifo_097;
extern App_queue Queue_DLCCH_idleRB_fifo_098;
extern App_queue Queue_DLCCH_idleRB_fifo_099;
extern App_queue Queue_DLCCH_idleRB_fifo_100;
extern App_queue Queue_DLCCH_idleRB_fifo_101;
extern App_queue Queue_DLCCH_idleRB_fifo_102;
extern App_queue Queue_DLCCH_idleRB_fifo_103;
extern App_queue Queue_DLCCH_idleRB_fifo_104;
extern App_queue Queue_DLCCH_idleRB_fifo_105;
extern App_queue Queue_DLCCH_idleRB_fifo_106;
extern App_queue Queue_DLCCH_idleRB_fifo_107;
extern App_queue Queue_DLCCH_idleRB_fifo_108;
extern App_queue Queue_DLCCH_idleRB_fifo_109;
extern App_queue Queue_DLCCH_idleRB_fifo_110;
extern App_queue Queue_DLCCH_idleRB_fifo_111;
extern App_queue Queue_DLCCH_idleRB_fifo_112;
extern App_queue Queue_DLCCH_idleRB_fifo_113;
extern App_queue Queue_DLCCH_idleRB_fifo_114;
extern App_queue Queue_DLCCH_idleRB_fifo_115;
extern App_queue Queue_DLCCH_idleRB_fifo_116;
extern App_queue Queue_DLCCH_idleRB_fifo_117;
extern App_queue Queue_DLCCH_idleRB_fifo_118;
extern App_queue Queue_DLCCH_idleRB_fifo_119;
extern App_queue Queue_DLCCH_idleRB_fifo_120;
extern App_queue Queue_DLCCH_idleRB_fifo_121;
extern App_queue Queue_DLCCH_idleRB_fifo_122;
extern App_queue Queue_DLCCH_idleRB_fifo_123;
extern App_queue Queue_DLCCH_idleRB_fifo_124;
extern App_queue Queue_DLCCH_idleRB_fifo_125;
extern App_queue Queue_DLCCH_idleRB_fifo_126;
extern App_queue Queue_DLCCH_idleRB_fifo_127;
extern App_queue Queue_DLCCH_idleRB_fifo_128;
extern App_queue Queue_DLCCH_idleRB_fifo_129;
extern App_queue Queue_DLCCH_idleRB_fifo_130;
extern App_queue Queue_DLCCH_idleRB_fifo_131;
extern App_queue Queue_DLCCH_idleRB_fifo_132;
extern App_queue Queue_DLCCH_idleRB_fifo_133;
extern App_queue Queue_DLCCH_idleRB_fifo_134;
extern App_queue Queue_DLCCH_idleRB_fifo_135;
extern App_queue Queue_DLCCH_idleRB_fifo_136;
extern App_queue Queue_DLCCH_idleRB_fifo_137;
extern App_queue Queue_DLCCH_idleRB_fifo_138;
extern App_queue Queue_DLCCH_idleRB_fifo_139;
extern App_queue Queue_DLCCH_idleRB_fifo_140;
extern App_queue Queue_DLCCH_idleRB_fifo_141;
extern App_queue Queue_DLCCH_idleRB_fifo_142;
extern App_queue Queue_DLCCH_idleRB_fifo_143;
extern App_queue Queue_DLCCH_idleRB_fifo_144;
extern App_queue Queue_DLCCH_idleRB_fifo_145;
extern App_queue Queue_DLCCH_idleRB_fifo_146;
extern App_queue Queue_DLCCH_idleRB_fifo_147;
extern App_queue Queue_DLCCH_idleRB_fifo_148;
extern App_queue Queue_DLCCH_idleRB_fifo_149;

extern App_queue Queue_ULSCH_idleRB_fifo_000;
extern App_queue Queue_ULSCH_idleRB_fifo_001;
extern App_queue Queue_ULSCH_idleRB_fifo_002;
extern App_queue Queue_ULSCH_idleRB_fifo_003;
extern App_queue Queue_ULSCH_idleRB_fifo_004;
extern App_queue Queue_ULSCH_idleRB_fifo_005;
extern App_queue Queue_ULSCH_idleRB_fifo_006;
extern App_queue Queue_ULSCH_idleRB_fifo_007;
extern App_queue Queue_ULSCH_idleRB_fifo_008;
extern App_queue Queue_ULSCH_idleRB_fifo_009;
extern App_queue Queue_ULSCH_idleRB_fifo_010;
extern App_queue Queue_ULSCH_idleRB_fifo_011;
extern App_queue Queue_ULSCH_idleRB_fifo_012;
extern App_queue Queue_ULSCH_idleRB_fifo_013;
extern App_queue Queue_ULSCH_idleRB_fifo_014;
extern App_queue Queue_ULSCH_idleRB_fifo_015;
extern App_queue Queue_ULSCH_idleRB_fifo_016;
extern App_queue Queue_ULSCH_idleRB_fifo_017;
extern App_queue Queue_ULSCH_idleRB_fifo_018;
extern App_queue Queue_ULSCH_idleRB_fifo_019;
extern App_queue Queue_ULSCH_idleRB_fifo_020;
extern App_queue Queue_ULSCH_idleRB_fifo_021;
extern App_queue Queue_ULSCH_idleRB_fifo_022;
extern App_queue Queue_ULSCH_idleRB_fifo_023;
extern App_queue Queue_ULSCH_idleRB_fifo_024;
extern App_queue Queue_ULSCH_idleRB_fifo_025;
extern App_queue Queue_ULSCH_idleRB_fifo_026;
extern App_queue Queue_ULSCH_idleRB_fifo_027;
extern App_queue Queue_ULSCH_idleRB_fifo_028;
extern App_queue Queue_ULSCH_idleRB_fifo_029;
extern App_queue Queue_ULSCH_idleRB_fifo_030;
extern App_queue Queue_ULSCH_idleRB_fifo_031;
extern App_queue Queue_ULSCH_idleRB_fifo_032;
extern App_queue Queue_ULSCH_idleRB_fifo_033;
extern App_queue Queue_ULSCH_idleRB_fifo_034;
extern App_queue Queue_ULSCH_idleRB_fifo_035;
extern App_queue Queue_ULSCH_idleRB_fifo_036;
extern App_queue Queue_ULSCH_idleRB_fifo_037;
extern App_queue Queue_ULSCH_idleRB_fifo_038;
extern App_queue Queue_ULSCH_idleRB_fifo_039;
extern App_queue Queue_ULSCH_idleRB_fifo_040;
extern App_queue Queue_ULSCH_idleRB_fifo_041;
extern App_queue Queue_ULSCH_idleRB_fifo_042;
extern App_queue Queue_ULSCH_idleRB_fifo_043;
extern App_queue Queue_ULSCH_idleRB_fifo_044;
extern App_queue Queue_ULSCH_idleRB_fifo_045;
extern App_queue Queue_ULSCH_idleRB_fifo_046;
extern App_queue Queue_ULSCH_idleRB_fifo_047;
extern App_queue Queue_ULSCH_idleRB_fifo_048;
extern App_queue Queue_ULSCH_idleRB_fifo_049;
extern App_queue Queue_ULSCH_idleRB_fifo_050;
extern App_queue Queue_ULSCH_idleRB_fifo_051;
extern App_queue Queue_ULSCH_idleRB_fifo_052;
extern App_queue Queue_ULSCH_idleRB_fifo_053;
extern App_queue Queue_ULSCH_idleRB_fifo_054;
extern App_queue Queue_ULSCH_idleRB_fifo_055;
extern App_queue Queue_ULSCH_idleRB_fifo_056;
extern App_queue Queue_ULSCH_idleRB_fifo_057;
extern App_queue Queue_ULSCH_idleRB_fifo_058;
extern App_queue Queue_ULSCH_idleRB_fifo_059;
extern App_queue Queue_ULSCH_idleRB_fifo_060;
extern App_queue Queue_ULSCH_idleRB_fifo_061;
extern App_queue Queue_ULSCH_idleRB_fifo_062;
extern App_queue Queue_ULSCH_idleRB_fifo_063;
extern App_queue Queue_ULSCH_idleRB_fifo_064;
extern App_queue Queue_ULSCH_idleRB_fifo_065;
extern App_queue Queue_ULSCH_idleRB_fifo_066;
extern App_queue Queue_ULSCH_idleRB_fifo_067;
extern App_queue Queue_ULSCH_idleRB_fifo_068;
extern App_queue Queue_ULSCH_idleRB_fifo_069;
extern App_queue Queue_ULSCH_idleRB_fifo_070;
extern App_queue Queue_ULSCH_idleRB_fifo_071;
extern App_queue Queue_ULSCH_idleRB_fifo_072;
extern App_queue Queue_ULSCH_idleRB_fifo_073;
extern App_queue Queue_ULSCH_idleRB_fifo_074;
extern App_queue Queue_ULSCH_idleRB_fifo_075;
extern App_queue Queue_ULSCH_idleRB_fifo_076;
extern App_queue Queue_ULSCH_idleRB_fifo_077;
extern App_queue Queue_ULSCH_idleRB_fifo_078;
extern App_queue Queue_ULSCH_idleRB_fifo_079;
extern App_queue Queue_ULSCH_idleRB_fifo_080;
extern App_queue Queue_ULSCH_idleRB_fifo_081;
extern App_queue Queue_ULSCH_idleRB_fifo_082;
extern App_queue Queue_ULSCH_idleRB_fifo_083;
extern App_queue Queue_ULSCH_idleRB_fifo_084;
extern App_queue Queue_ULSCH_idleRB_fifo_085;
extern App_queue Queue_ULSCH_idleRB_fifo_086;
extern App_queue Queue_ULSCH_idleRB_fifo_087;
extern App_queue Queue_ULSCH_idleRB_fifo_088;
extern App_queue Queue_ULSCH_idleRB_fifo_089;
extern App_queue Queue_ULSCH_idleRB_fifo_090;
extern App_queue Queue_ULSCH_idleRB_fifo_091;
extern App_queue Queue_ULSCH_idleRB_fifo_092;
extern App_queue Queue_ULSCH_idleRB_fifo_093;
extern App_queue Queue_ULSCH_idleRB_fifo_094;
extern App_queue Queue_ULSCH_idleRB_fifo_095;
extern App_queue Queue_ULSCH_idleRB_fifo_096;
extern App_queue Queue_ULSCH_idleRB_fifo_097;
extern App_queue Queue_ULSCH_idleRB_fifo_098;
extern App_queue Queue_ULSCH_idleRB_fifo_099;
extern App_queue Queue_ULSCH_idleRB_fifo_100;
extern App_queue Queue_ULSCH_idleRB_fifo_101;
extern App_queue Queue_ULSCH_idleRB_fifo_102;
extern App_queue Queue_ULSCH_idleRB_fifo_103;
extern App_queue Queue_ULSCH_idleRB_fifo_104;
extern App_queue Queue_ULSCH_idleRB_fifo_105;
extern App_queue Queue_ULSCH_idleRB_fifo_106;
extern App_queue Queue_ULSCH_idleRB_fifo_107;
extern App_queue Queue_ULSCH_idleRB_fifo_108;
extern App_queue Queue_ULSCH_idleRB_fifo_109;
extern App_queue Queue_ULSCH_idleRB_fifo_110;
extern App_queue Queue_ULSCH_idleRB_fifo_111;
extern App_queue Queue_ULSCH_idleRB_fifo_112;
extern App_queue Queue_ULSCH_idleRB_fifo_113;
extern App_queue Queue_ULSCH_idleRB_fifo_114;
extern App_queue Queue_ULSCH_idleRB_fifo_115;
extern App_queue Queue_ULSCH_idleRB_fifo_116;
extern App_queue Queue_ULSCH_idleRB_fifo_117;
extern App_queue Queue_ULSCH_idleRB_fifo_118;
extern App_queue Queue_ULSCH_idleRB_fifo_119;
extern App_queue Queue_ULSCH_idleRB_fifo_120;
extern App_queue Queue_ULSCH_idleRB_fifo_121;
extern App_queue Queue_ULSCH_idleRB_fifo_122;
extern App_queue Queue_ULSCH_idleRB_fifo_123;
extern App_queue Queue_ULSCH_idleRB_fifo_124;
extern App_queue Queue_ULSCH_idleRB_fifo_125;
extern App_queue Queue_ULSCH_idleRB_fifo_126;
extern App_queue Queue_ULSCH_idleRB_fifo_127;
extern App_queue Queue_ULSCH_idleRB_fifo_128;
extern App_queue Queue_ULSCH_idleRB_fifo_129;
extern App_queue Queue_ULSCH_idleRB_fifo_130;
extern App_queue Queue_ULSCH_idleRB_fifo_131;
extern App_queue Queue_ULSCH_idleRB_fifo_132;
extern App_queue Queue_ULSCH_idleRB_fifo_133;
extern App_queue Queue_ULSCH_idleRB_fifo_134;
extern App_queue Queue_ULSCH_idleRB_fifo_135;
extern App_queue Queue_ULSCH_idleRB_fifo_136;
extern App_queue Queue_ULSCH_idleRB_fifo_137;
extern App_queue Queue_ULSCH_idleRB_fifo_138;
extern App_queue Queue_ULSCH_idleRB_fifo_139;
extern App_queue Queue_ULSCH_idleRB_fifo_140;
extern App_queue Queue_ULSCH_idleRB_fifo_141;
extern App_queue Queue_ULSCH_idleRB_fifo_142;
extern App_queue Queue_ULSCH_idleRB_fifo_143;
extern App_queue Queue_ULSCH_idleRB_fifo_144;
extern App_queue Queue_ULSCH_idleRB_fifo_145;
extern App_queue Queue_ULSCH_idleRB_fifo_146;
extern App_queue Queue_ULSCH_idleRB_fifo_147;
extern App_queue Queue_ULSCH_idleRB_fifo_148;
extern App_queue Queue_ULSCH_idleRB_fifo_149;

extern App_queue Queue_DLSCH_idleRB_fifo_000;
extern App_queue Queue_DLSCH_idleRB_fifo_001;
extern App_queue Queue_DLSCH_idleRB_fifo_002;
extern App_queue Queue_DLSCH_idleRB_fifo_003;
extern App_queue Queue_DLSCH_idleRB_fifo_004;
extern App_queue Queue_DLSCH_idleRB_fifo_005;
extern App_queue Queue_DLSCH_idleRB_fifo_006;
extern App_queue Queue_DLSCH_idleRB_fifo_007;
extern App_queue Queue_DLSCH_idleRB_fifo_008;
extern App_queue Queue_DLSCH_idleRB_fifo_009;
extern App_queue Queue_DLSCH_idleRB_fifo_010;
extern App_queue Queue_DLSCH_idleRB_fifo_011;
extern App_queue Queue_DLSCH_idleRB_fifo_012;
extern App_queue Queue_DLSCH_idleRB_fifo_013;
extern App_queue Queue_DLSCH_idleRB_fifo_014;
extern App_queue Queue_DLSCH_idleRB_fifo_015;
extern App_queue Queue_DLSCH_idleRB_fifo_016;
extern App_queue Queue_DLSCH_idleRB_fifo_017;
extern App_queue Queue_DLSCH_idleRB_fifo_018;
extern App_queue Queue_DLSCH_idleRB_fifo_019;
extern App_queue Queue_DLSCH_idleRB_fifo_020;
extern App_queue Queue_DLSCH_idleRB_fifo_021;
extern App_queue Queue_DLSCH_idleRB_fifo_022;
extern App_queue Queue_DLSCH_idleRB_fifo_023;
extern App_queue Queue_DLSCH_idleRB_fifo_024;
extern App_queue Queue_DLSCH_idleRB_fifo_025;
extern App_queue Queue_DLSCH_idleRB_fifo_026;
extern App_queue Queue_DLSCH_idleRB_fifo_027;
extern App_queue Queue_DLSCH_idleRB_fifo_028;
extern App_queue Queue_DLSCH_idleRB_fifo_029;
extern App_queue Queue_DLSCH_idleRB_fifo_030;
extern App_queue Queue_DLSCH_idleRB_fifo_031;
extern App_queue Queue_DLSCH_idleRB_fifo_032;
extern App_queue Queue_DLSCH_idleRB_fifo_033;
extern App_queue Queue_DLSCH_idleRB_fifo_034;
extern App_queue Queue_DLSCH_idleRB_fifo_035;
extern App_queue Queue_DLSCH_idleRB_fifo_036;
extern App_queue Queue_DLSCH_idleRB_fifo_037;
extern App_queue Queue_DLSCH_idleRB_fifo_038;
extern App_queue Queue_DLSCH_idleRB_fifo_039;
extern App_queue Queue_DLSCH_idleRB_fifo_040;
extern App_queue Queue_DLSCH_idleRB_fifo_041;
extern App_queue Queue_DLSCH_idleRB_fifo_042;
extern App_queue Queue_DLSCH_idleRB_fifo_043;
extern App_queue Queue_DLSCH_idleRB_fifo_044;
extern App_queue Queue_DLSCH_idleRB_fifo_045;
extern App_queue Queue_DLSCH_idleRB_fifo_046;
extern App_queue Queue_DLSCH_idleRB_fifo_047;
extern App_queue Queue_DLSCH_idleRB_fifo_048;
extern App_queue Queue_DLSCH_idleRB_fifo_049;
extern App_queue Queue_DLSCH_idleRB_fifo_050;
extern App_queue Queue_DLSCH_idleRB_fifo_051;
extern App_queue Queue_DLSCH_idleRB_fifo_052;
extern App_queue Queue_DLSCH_idleRB_fifo_053;
extern App_queue Queue_DLSCH_idleRB_fifo_054;
extern App_queue Queue_DLSCH_idleRB_fifo_055;
extern App_queue Queue_DLSCH_idleRB_fifo_056;
extern App_queue Queue_DLSCH_idleRB_fifo_057;
extern App_queue Queue_DLSCH_idleRB_fifo_058;
extern App_queue Queue_DLSCH_idleRB_fifo_059;
extern App_queue Queue_DLSCH_idleRB_fifo_060;
extern App_queue Queue_DLSCH_idleRB_fifo_061;
extern App_queue Queue_DLSCH_idleRB_fifo_062;
extern App_queue Queue_DLSCH_idleRB_fifo_063;
extern App_queue Queue_DLSCH_idleRB_fifo_064;
extern App_queue Queue_DLSCH_idleRB_fifo_065;
extern App_queue Queue_DLSCH_idleRB_fifo_066;
extern App_queue Queue_DLSCH_idleRB_fifo_067;
extern App_queue Queue_DLSCH_idleRB_fifo_068;
extern App_queue Queue_DLSCH_idleRB_fifo_069;
extern App_queue Queue_DLSCH_idleRB_fifo_070;
extern App_queue Queue_DLSCH_idleRB_fifo_071;
extern App_queue Queue_DLSCH_idleRB_fifo_072;
extern App_queue Queue_DLSCH_idleRB_fifo_073;
extern App_queue Queue_DLSCH_idleRB_fifo_074;
extern App_queue Queue_DLSCH_idleRB_fifo_075;
extern App_queue Queue_DLSCH_idleRB_fifo_076;
extern App_queue Queue_DLSCH_idleRB_fifo_077;
extern App_queue Queue_DLSCH_idleRB_fifo_078;
extern App_queue Queue_DLSCH_idleRB_fifo_079;
extern App_queue Queue_DLSCH_idleRB_fifo_080;
extern App_queue Queue_DLSCH_idleRB_fifo_081;
extern App_queue Queue_DLSCH_idleRB_fifo_082;
extern App_queue Queue_DLSCH_idleRB_fifo_083;
extern App_queue Queue_DLSCH_idleRB_fifo_084;
extern App_queue Queue_DLSCH_idleRB_fifo_085;
extern App_queue Queue_DLSCH_idleRB_fifo_086;
extern App_queue Queue_DLSCH_idleRB_fifo_087;
extern App_queue Queue_DLSCH_idleRB_fifo_088;
extern App_queue Queue_DLSCH_idleRB_fifo_089;
extern App_queue Queue_DLSCH_idleRB_fifo_090;
extern App_queue Queue_DLSCH_idleRB_fifo_091;
extern App_queue Queue_DLSCH_idleRB_fifo_092;
extern App_queue Queue_DLSCH_idleRB_fifo_093;
extern App_queue Queue_DLSCH_idleRB_fifo_094;
extern App_queue Queue_DLSCH_idleRB_fifo_095;
extern App_queue Queue_DLSCH_idleRB_fifo_096;
extern App_queue Queue_DLSCH_idleRB_fifo_097;
extern App_queue Queue_DLSCH_idleRB_fifo_098;
extern App_queue Queue_DLSCH_idleRB_fifo_099;
extern App_queue Queue_DLSCH_idleRB_fifo_100;
extern App_queue Queue_DLSCH_idleRB_fifo_101;
extern App_queue Queue_DLSCH_idleRB_fifo_102;
extern App_queue Queue_DLSCH_idleRB_fifo_103;
extern App_queue Queue_DLSCH_idleRB_fifo_104;
extern App_queue Queue_DLSCH_idleRB_fifo_105;
extern App_queue Queue_DLSCH_idleRB_fifo_106;
extern App_queue Queue_DLSCH_idleRB_fifo_107;
extern App_queue Queue_DLSCH_idleRB_fifo_108;
extern App_queue Queue_DLSCH_idleRB_fifo_109;
extern App_queue Queue_DLSCH_idleRB_fifo_110;
extern App_queue Queue_DLSCH_idleRB_fifo_111;
extern App_queue Queue_DLSCH_idleRB_fifo_112;
extern App_queue Queue_DLSCH_idleRB_fifo_113;
extern App_queue Queue_DLSCH_idleRB_fifo_114;
extern App_queue Queue_DLSCH_idleRB_fifo_115;
extern App_queue Queue_DLSCH_idleRB_fifo_116;
extern App_queue Queue_DLSCH_idleRB_fifo_117;
extern App_queue Queue_DLSCH_idleRB_fifo_118;
extern App_queue Queue_DLSCH_idleRB_fifo_119;
extern App_queue Queue_DLSCH_idleRB_fifo_120;
extern App_queue Queue_DLSCH_idleRB_fifo_121;
extern App_queue Queue_DLSCH_idleRB_fifo_122;
extern App_queue Queue_DLSCH_idleRB_fifo_123;
extern App_queue Queue_DLSCH_idleRB_fifo_124;
extern App_queue Queue_DLSCH_idleRB_fifo_125;
extern App_queue Queue_DLSCH_idleRB_fifo_126;
extern App_queue Queue_DLSCH_idleRB_fifo_127;
extern App_queue Queue_DLSCH_idleRB_fifo_128;
extern App_queue Queue_DLSCH_idleRB_fifo_129;
extern App_queue Queue_DLSCH_idleRB_fifo_130;
extern App_queue Queue_DLSCH_idleRB_fifo_131;
extern App_queue Queue_DLSCH_idleRB_fifo_132;
extern App_queue Queue_DLSCH_idleRB_fifo_133;
extern App_queue Queue_DLSCH_idleRB_fifo_134;
extern App_queue Queue_DLSCH_idleRB_fifo_135;
extern App_queue Queue_DLSCH_idleRB_fifo_136;
extern App_queue Queue_DLSCH_idleRB_fifo_137;
extern App_queue Queue_DLSCH_idleRB_fifo_138;
extern App_queue Queue_DLSCH_idleRB_fifo_139;
extern App_queue Queue_DLSCH_idleRB_fifo_140;
extern App_queue Queue_DLSCH_idleRB_fifo_141;
extern App_queue Queue_DLSCH_idleRB_fifo_142;
extern App_queue Queue_DLSCH_idleRB_fifo_143;
extern App_queue Queue_DLSCH_idleRB_fifo_144;
extern App_queue Queue_DLSCH_idleRB_fifo_145;
extern App_queue Queue_DLSCH_idleRB_fifo_146;
extern App_queue Queue_DLSCH_idleRB_fifo_147;
extern App_queue Queue_DLSCH_idleRB_fifo_148;
extern App_queue Queue_DLSCH_idleRB_fifo_149;

// 下行业务队列，每个队列放对应虚波位的所有业务（不区分业务类型、不区分用户）
extern App_queue Queue_DL_BusinessPackage_000;
extern App_queue Queue_DL_BusinessPackage_001;
extern App_queue Queue_DL_BusinessPackage_002;
extern App_queue Queue_DL_BusinessPackage_003;
extern App_queue Queue_DL_BusinessPackage_004;
extern App_queue Queue_DL_BusinessPackage_005;
extern App_queue Queue_DL_BusinessPackage_006;
extern App_queue Queue_DL_BusinessPackage_007;
extern App_queue Queue_DL_BusinessPackage_008;
extern App_queue Queue_DL_BusinessPackage_009;
extern App_queue Queue_DL_BusinessPackage_010;
extern App_queue Queue_DL_BusinessPackage_011;
extern App_queue Queue_DL_BusinessPackage_012;
extern App_queue Queue_DL_BusinessPackage_013;
extern App_queue Queue_DL_BusinessPackage_014;
extern App_queue Queue_DL_BusinessPackage_015;
extern App_queue Queue_DL_BusinessPackage_016;
extern App_queue Queue_DL_BusinessPackage_017;
extern App_queue Queue_DL_BusinessPackage_018;
extern App_queue Queue_DL_BusinessPackage_019;
extern App_queue Queue_DL_BusinessPackage_020;
extern App_queue Queue_DL_BusinessPackage_021;
extern App_queue Queue_DL_BusinessPackage_022;
extern App_queue Queue_DL_BusinessPackage_023;
extern App_queue Queue_DL_BusinessPackage_024;
extern App_queue Queue_DL_BusinessPackage_025;
extern App_queue Queue_DL_BusinessPackage_026;
extern App_queue Queue_DL_BusinessPackage_027;
extern App_queue Queue_DL_BusinessPackage_028;
extern App_queue Queue_DL_BusinessPackage_029;
extern App_queue Queue_DL_BusinessPackage_030;
extern App_queue Queue_DL_BusinessPackage_031;
extern App_queue Queue_DL_BusinessPackage_032;
extern App_queue Queue_DL_BusinessPackage_033;
extern App_queue Queue_DL_BusinessPackage_034;
extern App_queue Queue_DL_BusinessPackage_035;
extern App_queue Queue_DL_BusinessPackage_036;
extern App_queue Queue_DL_BusinessPackage_037;
extern App_queue Queue_DL_BusinessPackage_038;
extern App_queue Queue_DL_BusinessPackage_039;
extern App_queue Queue_DL_BusinessPackage_040;
extern App_queue Queue_DL_BusinessPackage_041;
extern App_queue Queue_DL_BusinessPackage_042;
extern App_queue Queue_DL_BusinessPackage_043;
extern App_queue Queue_DL_BusinessPackage_044;
extern App_queue Queue_DL_BusinessPackage_045;
extern App_queue Queue_DL_BusinessPackage_046;
extern App_queue Queue_DL_BusinessPackage_047;
extern App_queue Queue_DL_BusinessPackage_048;
extern App_queue Queue_DL_BusinessPackage_049;
extern App_queue Queue_DL_BusinessPackage_050;
extern App_queue Queue_DL_BusinessPackage_051;
extern App_queue Queue_DL_BusinessPackage_052;
extern App_queue Queue_DL_BusinessPackage_053;
extern App_queue Queue_DL_BusinessPackage_054;
extern App_queue Queue_DL_BusinessPackage_055;
extern App_queue Queue_DL_BusinessPackage_056;
extern App_queue Queue_DL_BusinessPackage_057;
extern App_queue Queue_DL_BusinessPackage_058;
extern App_queue Queue_DL_BusinessPackage_059;
extern App_queue Queue_DL_BusinessPackage_060;
extern App_queue Queue_DL_BusinessPackage_061;
extern App_queue Queue_DL_BusinessPackage_062;
extern App_queue Queue_DL_BusinessPackage_063;
extern App_queue Queue_DL_BusinessPackage_064;
extern App_queue Queue_DL_BusinessPackage_065;
extern App_queue Queue_DL_BusinessPackage_066;
extern App_queue Queue_DL_BusinessPackage_067;
extern App_queue Queue_DL_BusinessPackage_068;
extern App_queue Queue_DL_BusinessPackage_069;
extern App_queue Queue_DL_BusinessPackage_070;
extern App_queue Queue_DL_BusinessPackage_071;
extern App_queue Queue_DL_BusinessPackage_072;
extern App_queue Queue_DL_BusinessPackage_073;
extern App_queue Queue_DL_BusinessPackage_074;
extern App_queue Queue_DL_BusinessPackage_075;
extern App_queue Queue_DL_BusinessPackage_076;
extern App_queue Queue_DL_BusinessPackage_077;
extern App_queue Queue_DL_BusinessPackage_078;
extern App_queue Queue_DL_BusinessPackage_079;
extern App_queue Queue_DL_BusinessPackage_080;
extern App_queue Queue_DL_BusinessPackage_081;
extern App_queue Queue_DL_BusinessPackage_082;
extern App_queue Queue_DL_BusinessPackage_083;
extern App_queue Queue_DL_BusinessPackage_084;
extern App_queue Queue_DL_BusinessPackage_085;
extern App_queue Queue_DL_BusinessPackage_086;
extern App_queue Queue_DL_BusinessPackage_087;
extern App_queue Queue_DL_BusinessPackage_088;
extern App_queue Queue_DL_BusinessPackage_089;
extern App_queue Queue_DL_BusinessPackage_090;
extern App_queue Queue_DL_BusinessPackage_091;
extern App_queue Queue_DL_BusinessPackage_092;
extern App_queue Queue_DL_BusinessPackage_093;
extern App_queue Queue_DL_BusinessPackage_094;
extern App_queue Queue_DL_BusinessPackage_095;
extern App_queue Queue_DL_BusinessPackage_096;
extern App_queue Queue_DL_BusinessPackage_097;
extern App_queue Queue_DL_BusinessPackage_098;
extern App_queue Queue_DL_BusinessPackage_099;
extern App_queue Queue_DL_BusinessPackage_100;
extern App_queue Queue_DL_BusinessPackage_101;
extern App_queue Queue_DL_BusinessPackage_102;
extern App_queue Queue_DL_BusinessPackage_103;
extern App_queue Queue_DL_BusinessPackage_104;
extern App_queue Queue_DL_BusinessPackage_105;
extern App_queue Queue_DL_BusinessPackage_106;
extern App_queue Queue_DL_BusinessPackage_107;
extern App_queue Queue_DL_BusinessPackage_108;
extern App_queue Queue_DL_BusinessPackage_109;
extern App_queue Queue_DL_BusinessPackage_110;
extern App_queue Queue_DL_BusinessPackage_111;
extern App_queue Queue_DL_BusinessPackage_112;
extern App_queue Queue_DL_BusinessPackage_113;
extern App_queue Queue_DL_BusinessPackage_114;
extern App_queue Queue_DL_BusinessPackage_115;
extern App_queue Queue_DL_BusinessPackage_116;
extern App_queue Queue_DL_BusinessPackage_117;
extern App_queue Queue_DL_BusinessPackage_118;
extern App_queue Queue_DL_BusinessPackage_119;
extern App_queue Queue_DL_BusinessPackage_120;
extern App_queue Queue_DL_BusinessPackage_121;
extern App_queue Queue_DL_BusinessPackage_122;
extern App_queue Queue_DL_BusinessPackage_123;
extern App_queue Queue_DL_BusinessPackage_124;
extern App_queue Queue_DL_BusinessPackage_125;
extern App_queue Queue_DL_BusinessPackage_126;
extern App_queue Queue_DL_BusinessPackage_127;
extern App_queue Queue_DL_BusinessPackage_128;
extern App_queue Queue_DL_BusinessPackage_129;
extern App_queue Queue_DL_BusinessPackage_130;
extern App_queue Queue_DL_BusinessPackage_131;
extern App_queue Queue_DL_BusinessPackage_132;
extern App_queue Queue_DL_BusinessPackage_133;
extern App_queue Queue_DL_BusinessPackage_134;
extern App_queue Queue_DL_BusinessPackage_135;
extern App_queue Queue_DL_BusinessPackage_136;
extern App_queue Queue_DL_BusinessPackage_137;
extern App_queue Queue_DL_BusinessPackage_138;
extern App_queue Queue_DL_BusinessPackage_139;
extern App_queue Queue_DL_BusinessPackage_140;
extern App_queue Queue_DL_BusinessPackage_141;
extern App_queue Queue_DL_BusinessPackage_142;
extern App_queue Queue_DL_BusinessPackage_143;
extern App_queue Queue_DL_BusinessPackage_144;
extern App_queue Queue_DL_BusinessPackage_145;
extern App_queue Queue_DL_BusinessPackage_146;
extern App_queue Queue_DL_BusinessPackage_147;
extern App_queue Queue_DL_BusinessPackage_148;
extern App_queue Queue_DL_BusinessPackage_149;

// 下行控制队列，每个队列放对应虚波位的所有业务（不区分业务类型、不区分用户）
extern App_queue Queue_DL_ControlPackage_000;
extern App_queue Queue_DL_ControlPackage_001;
extern App_queue Queue_DL_ControlPackage_002;
extern App_queue Queue_DL_ControlPackage_003;
extern App_queue Queue_DL_ControlPackage_004;
extern App_queue Queue_DL_ControlPackage_005;
extern App_queue Queue_DL_ControlPackage_006;
extern App_queue Queue_DL_ControlPackage_007;
extern App_queue Queue_DL_ControlPackage_008;
extern App_queue Queue_DL_ControlPackage_009;
extern App_queue Queue_DL_ControlPackage_010;
extern App_queue Queue_DL_ControlPackage_011;
extern App_queue Queue_DL_ControlPackage_012;
extern App_queue Queue_DL_ControlPackage_013;
extern App_queue Queue_DL_ControlPackage_014;
extern App_queue Queue_DL_ControlPackage_015;
extern App_queue Queue_DL_ControlPackage_016;
extern App_queue Queue_DL_ControlPackage_017;
extern App_queue Queue_DL_ControlPackage_018;
extern App_queue Queue_DL_ControlPackage_019;
extern App_queue Queue_DL_ControlPackage_020;
extern App_queue Queue_DL_ControlPackage_021;
extern App_queue Queue_DL_ControlPackage_022;
extern App_queue Queue_DL_ControlPackage_023;
extern App_queue Queue_DL_ControlPackage_024;
extern App_queue Queue_DL_ControlPackage_025;
extern App_queue Queue_DL_ControlPackage_026;
extern App_queue Queue_DL_ControlPackage_027;
extern App_queue Queue_DL_ControlPackage_028;
extern App_queue Queue_DL_ControlPackage_029;
extern App_queue Queue_DL_ControlPackage_030;
extern App_queue Queue_DL_ControlPackage_031;
extern App_queue Queue_DL_ControlPackage_032;
extern App_queue Queue_DL_ControlPackage_033;
extern App_queue Queue_DL_ControlPackage_034;
extern App_queue Queue_DL_ControlPackage_035;
extern App_queue Queue_DL_ControlPackage_036;
extern App_queue Queue_DL_ControlPackage_037;
extern App_queue Queue_DL_ControlPackage_038;
extern App_queue Queue_DL_ControlPackage_039;
extern App_queue Queue_DL_ControlPackage_040;
extern App_queue Queue_DL_ControlPackage_041;
extern App_queue Queue_DL_ControlPackage_042;
extern App_queue Queue_DL_ControlPackage_043;
extern App_queue Queue_DL_ControlPackage_044;
extern App_queue Queue_DL_ControlPackage_045;
extern App_queue Queue_DL_ControlPackage_046;
extern App_queue Queue_DL_ControlPackage_047;
extern App_queue Queue_DL_ControlPackage_048;
extern App_queue Queue_DL_ControlPackage_049;
extern App_queue Queue_DL_ControlPackage_050;
extern App_queue Queue_DL_ControlPackage_051;
extern App_queue Queue_DL_ControlPackage_052;
extern App_queue Queue_DL_ControlPackage_053;
extern App_queue Queue_DL_ControlPackage_054;
extern App_queue Queue_DL_ControlPackage_055;
extern App_queue Queue_DL_ControlPackage_056;
extern App_queue Queue_DL_ControlPackage_057;
extern App_queue Queue_DL_ControlPackage_058;
extern App_queue Queue_DL_ControlPackage_059;
extern App_queue Queue_DL_ControlPackage_060;
extern App_queue Queue_DL_ControlPackage_061;
extern App_queue Queue_DL_ControlPackage_062;
extern App_queue Queue_DL_ControlPackage_063;
extern App_queue Queue_DL_ControlPackage_064;
extern App_queue Queue_DL_ControlPackage_065;
extern App_queue Queue_DL_ControlPackage_066;
extern App_queue Queue_DL_ControlPackage_067;
extern App_queue Queue_DL_ControlPackage_068;
extern App_queue Queue_DL_ControlPackage_069;
extern App_queue Queue_DL_ControlPackage_070;
extern App_queue Queue_DL_ControlPackage_071;
extern App_queue Queue_DL_ControlPackage_072;
extern App_queue Queue_DL_ControlPackage_073;
extern App_queue Queue_DL_ControlPackage_074;
extern App_queue Queue_DL_ControlPackage_075;
extern App_queue Queue_DL_ControlPackage_076;
extern App_queue Queue_DL_ControlPackage_077;
extern App_queue Queue_DL_ControlPackage_078;
extern App_queue Queue_DL_ControlPackage_079;
extern App_queue Queue_DL_ControlPackage_080;
extern App_queue Queue_DL_ControlPackage_081;
extern App_queue Queue_DL_ControlPackage_082;
extern App_queue Queue_DL_ControlPackage_083;
extern App_queue Queue_DL_ControlPackage_084;
extern App_queue Queue_DL_ControlPackage_085;
extern App_queue Queue_DL_ControlPackage_086;
extern App_queue Queue_DL_ControlPackage_087;
extern App_queue Queue_DL_ControlPackage_088;
extern App_queue Queue_DL_ControlPackage_089;
extern App_queue Queue_DL_ControlPackage_090;
extern App_queue Queue_DL_ControlPackage_091;
extern App_queue Queue_DL_ControlPackage_092;
extern App_queue Queue_DL_ControlPackage_093;
extern App_queue Queue_DL_ControlPackage_094;
extern App_queue Queue_DL_ControlPackage_095;
extern App_queue Queue_DL_ControlPackage_096;
extern App_queue Queue_DL_ControlPackage_097;
extern App_queue Queue_DL_ControlPackage_098;
extern App_queue Queue_DL_ControlPackage_099;
extern App_queue Queue_DL_ControlPackage_100;
extern App_queue Queue_DL_ControlPackage_101;
extern App_queue Queue_DL_ControlPackage_102;
extern App_queue Queue_DL_ControlPackage_103;
extern App_queue Queue_DL_ControlPackage_104;
extern App_queue Queue_DL_ControlPackage_105;
extern App_queue Queue_DL_ControlPackage_106;
extern App_queue Queue_DL_ControlPackage_107;
extern App_queue Queue_DL_ControlPackage_108;
extern App_queue Queue_DL_ControlPackage_109;
extern App_queue Queue_DL_ControlPackage_110;
extern App_queue Queue_DL_ControlPackage_111;
extern App_queue Queue_DL_ControlPackage_112;
extern App_queue Queue_DL_ControlPackage_113;
extern App_queue Queue_DL_ControlPackage_114;
extern App_queue Queue_DL_ControlPackage_115;
extern App_queue Queue_DL_ControlPackage_116;
extern App_queue Queue_DL_ControlPackage_117;
extern App_queue Queue_DL_ControlPackage_118;
extern App_queue Queue_DL_ControlPackage_119;
extern App_queue Queue_DL_ControlPackage_120;
extern App_queue Queue_DL_ControlPackage_121;
extern App_queue Queue_DL_ControlPackage_122;
extern App_queue Queue_DL_ControlPackage_123;
extern App_queue Queue_DL_ControlPackage_124;
extern App_queue Queue_DL_ControlPackage_125;
extern App_queue Queue_DL_ControlPackage_126;
extern App_queue Queue_DL_ControlPackage_127;
extern App_queue Queue_DL_ControlPackage_128;
extern App_queue Queue_DL_ControlPackage_129;
extern App_queue Queue_DL_ControlPackage_130;
extern App_queue Queue_DL_ControlPackage_131;
extern App_queue Queue_DL_ControlPackage_132;
extern App_queue Queue_DL_ControlPackage_133;
extern App_queue Queue_DL_ControlPackage_134;
extern App_queue Queue_DL_ControlPackage_135;
extern App_queue Queue_DL_ControlPackage_136;
extern App_queue Queue_DL_ControlPackage_137;
extern App_queue Queue_DL_ControlPackage_138;
extern App_queue Queue_DL_ControlPackage_139;
extern App_queue Queue_DL_ControlPackage_140;
extern App_queue Queue_DL_ControlPackage_141;
extern App_queue Queue_DL_ControlPackage_142;
extern App_queue Queue_DL_ControlPackage_143;
extern App_queue Queue_DL_ControlPackage_144;
extern App_queue Queue_DL_ControlPackage_145;
extern App_queue Queue_DL_ControlPackage_146;
extern App_queue Queue_DL_ControlPackage_147;
extern App_queue Queue_DL_ControlPackage_148;
extern App_queue Queue_DL_ControlPackage_149;

extern App_queue Queue_UE_data_recv_000;
extern App_queue Queue_UE_data_recv_001;
extern App_queue Queue_UE_data_recv_002;
extern App_queue Queue_UE_data_recv_003;
extern App_queue Queue_UE_data_recv_004;
extern App_queue Queue_UE_data_recv_005;
extern App_queue Queue_UE_data_recv_006;
extern App_queue Queue_UE_data_recv_007;
extern App_queue Queue_UE_data_recv_008;
extern App_queue Queue_UE_data_recv_009;
extern App_queue Queue_UE_data_recv_010;
extern App_queue Queue_UE_data_recv_011;
extern App_queue Queue_UE_data_recv_012;
extern App_queue Queue_UE_data_recv_013;
extern App_queue Queue_UE_data_recv_014;
extern App_queue Queue_UE_data_recv_015;
extern App_queue Queue_UE_data_recv_016;
extern App_queue Queue_UE_data_recv_017;
extern App_queue Queue_UE_data_recv_018;
extern App_queue Queue_UE_data_recv_019;
extern App_queue Queue_UE_data_recv_020;
extern App_queue Queue_UE_data_recv_021;
extern App_queue Queue_UE_data_recv_022;
extern App_queue Queue_UE_data_recv_023;
extern App_queue Queue_UE_data_recv_024;
extern App_queue Queue_UE_data_recv_025;
extern App_queue Queue_UE_data_recv_026;
extern App_queue Queue_UE_data_recv_027;
extern App_queue Queue_UE_data_recv_028;
extern App_queue Queue_UE_data_recv_029;
extern App_queue Queue_UE_data_recv_030;
extern App_queue Queue_UE_data_recv_031;
extern App_queue Queue_UE_data_recv_032;
extern App_queue Queue_UE_data_recv_033;
extern App_queue Queue_UE_data_recv_034;
extern App_queue Queue_UE_data_recv_035;
extern App_queue Queue_UE_data_recv_036;
extern App_queue Queue_UE_data_recv_037;
extern App_queue Queue_UE_data_recv_038;
extern App_queue Queue_UE_data_recv_039;
extern App_queue Queue_UE_data_recv_040;
extern App_queue Queue_UE_data_recv_041;
extern App_queue Queue_UE_data_recv_042;
extern App_queue Queue_UE_data_recv_043;
extern App_queue Queue_UE_data_recv_044;
extern App_queue Queue_UE_data_recv_045;
extern App_queue Queue_UE_data_recv_046;
extern App_queue Queue_UE_data_recv_047;
extern App_queue Queue_UE_data_recv_048;
extern App_queue Queue_UE_data_recv_049;
extern App_queue Queue_UE_data_recv_050;
extern App_queue Queue_UE_data_recv_051;
extern App_queue Queue_UE_data_recv_052;
extern App_queue Queue_UE_data_recv_053;
extern App_queue Queue_UE_data_recv_054;
extern App_queue Queue_UE_data_recv_055;
extern App_queue Queue_UE_data_recv_056;
extern App_queue Queue_UE_data_recv_057;
extern App_queue Queue_UE_data_recv_058;
extern App_queue Queue_UE_data_recv_059;
extern App_queue Queue_UE_data_recv_060;
extern App_queue Queue_UE_data_recv_061;
extern App_queue Queue_UE_data_recv_062;
extern App_queue Queue_UE_data_recv_063;
extern App_queue Queue_UE_data_recv_064;
extern App_queue Queue_UE_data_recv_065;
extern App_queue Queue_UE_data_recv_066;
extern App_queue Queue_UE_data_recv_067;
extern App_queue Queue_UE_data_recv_068;
extern App_queue Queue_UE_data_recv_069;
extern App_queue Queue_UE_data_recv_070;
extern App_queue Queue_UE_data_recv_071;
extern App_queue Queue_UE_data_recv_072;
extern App_queue Queue_UE_data_recv_073;
extern App_queue Queue_UE_data_recv_074;
extern App_queue Queue_UE_data_recv_075;
extern App_queue Queue_UE_data_recv_076;
extern App_queue Queue_UE_data_recv_077;
extern App_queue Queue_UE_data_recv_078;
extern App_queue Queue_UE_data_recv_079;
extern App_queue Queue_UE_data_recv_080;
extern App_queue Queue_UE_data_recv_081;
extern App_queue Queue_UE_data_recv_082;
extern App_queue Queue_UE_data_recv_083;
extern App_queue Queue_UE_data_recv_084;
extern App_queue Queue_UE_data_recv_085;
extern App_queue Queue_UE_data_recv_086;
extern App_queue Queue_UE_data_recv_087;
extern App_queue Queue_UE_data_recv_088;
extern App_queue Queue_UE_data_recv_089;
extern App_queue Queue_UE_data_recv_090;
extern App_queue Queue_UE_data_recv_091;
extern App_queue Queue_UE_data_recv_092;
extern App_queue Queue_UE_data_recv_093;
extern App_queue Queue_UE_data_recv_094;
extern App_queue Queue_UE_data_recv_095;
extern App_queue Queue_UE_data_recv_096;
extern App_queue Queue_UE_data_recv_097;
extern App_queue Queue_UE_data_recv_098;
extern App_queue Queue_UE_data_recv_099;
extern App_queue Queue_UE_data_recv_100;
extern App_queue Queue_UE_data_recv_101;
extern App_queue Queue_UE_data_recv_102;
extern App_queue Queue_UE_data_recv_103;
extern App_queue Queue_UE_data_recv_104;
extern App_queue Queue_UE_data_recv_105;
extern App_queue Queue_UE_data_recv_106;
extern App_queue Queue_UE_data_recv_107;
extern App_queue Queue_UE_data_recv_108;
extern App_queue Queue_UE_data_recv_109;
extern App_queue Queue_UE_data_recv_110;
extern App_queue Queue_UE_data_recv_111;
extern App_queue Queue_UE_data_recv_112;
extern App_queue Queue_UE_data_recv_113;
extern App_queue Queue_UE_data_recv_114;
extern App_queue Queue_UE_data_recv_115;
extern App_queue Queue_UE_data_recv_116;
extern App_queue Queue_UE_data_recv_117;
extern App_queue Queue_UE_data_recv_118;
extern App_queue Queue_UE_data_recv_119;
extern App_queue Queue_UE_data_recv_120;
extern App_queue Queue_UE_data_recv_121;
extern App_queue Queue_UE_data_recv_122;
extern App_queue Queue_UE_data_recv_123;
extern App_queue Queue_UE_data_recv_124;
extern App_queue Queue_UE_data_recv_125;
extern App_queue Queue_UE_data_recv_126;
extern App_queue Queue_UE_data_recv_127;
extern App_queue Queue_UE_data_recv_128;
extern App_queue Queue_UE_data_recv_129;
extern App_queue Queue_UE_data_recv_130;
extern App_queue Queue_UE_data_recv_131;
extern App_queue Queue_UE_data_recv_132;
extern App_queue Queue_UE_data_recv_133;
extern App_queue Queue_UE_data_recv_134;
extern App_queue Queue_UE_data_recv_135;
extern App_queue Queue_UE_data_recv_136;
extern App_queue Queue_UE_data_recv_137;
extern App_queue Queue_UE_data_recv_138;
extern App_queue Queue_UE_data_recv_139;
extern App_queue Queue_UE_data_recv_140;
extern App_queue Queue_UE_data_recv_141;
extern App_queue Queue_UE_data_recv_142;
extern App_queue Queue_UE_data_recv_143;
extern App_queue Queue_UE_data_recv_144;
extern App_queue Queue_UE_data_recv_145;
extern App_queue Queue_UE_data_recv_146;
extern App_queue Queue_UE_data_recv_147;
extern App_queue Queue_UE_data_recv_148;
extern App_queue Queue_UE_data_recv_149;
extern App_queue Queue_UE_data_recv_150;
extern App_queue Queue_UE_data_recv_151;
extern App_queue Queue_UE_data_recv_152;
extern App_queue Queue_UE_data_recv_153;
extern App_queue Queue_UE_data_recv_154;
extern App_queue Queue_UE_data_recv_155;
extern App_queue Queue_UE_data_recv_156;
extern App_queue Queue_UE_data_recv_157;
extern App_queue Queue_UE_data_recv_158;
extern App_queue Queue_UE_data_recv_159;
extern App_queue Queue_UE_data_recv_160;
extern App_queue Queue_UE_data_recv_161;
extern App_queue Queue_UE_data_recv_162;
extern App_queue Queue_UE_data_recv_163;
extern App_queue Queue_UE_data_recv_164;
extern App_queue Queue_UE_data_recv_165;
extern App_queue Queue_UE_data_recv_166;
extern App_queue Queue_UE_data_recv_167;
extern App_queue Queue_UE_data_recv_168;
extern App_queue Queue_UE_data_recv_169;
extern App_queue Queue_UE_data_recv_170;
extern App_queue Queue_UE_data_recv_171;
extern App_queue Queue_UE_data_recv_172;
extern App_queue Queue_UE_data_recv_173;
extern App_queue Queue_UE_data_recv_174;
extern App_queue Queue_UE_data_recv_175;
extern App_queue Queue_UE_data_recv_176;
extern App_queue Queue_UE_data_recv_177;
extern App_queue Queue_UE_data_recv_178;
extern App_queue Queue_UE_data_recv_179;
extern App_queue Queue_UE_data_recv_180;
extern App_queue Queue_UE_data_recv_181;
extern App_queue Queue_UE_data_recv_182;
extern App_queue Queue_UE_data_recv_183;
extern App_queue Queue_UE_data_recv_184;
extern App_queue Queue_UE_data_recv_185;
extern App_queue Queue_UE_data_recv_186;
extern App_queue Queue_UE_data_recv_187;
extern App_queue Queue_UE_data_recv_188;
extern App_queue Queue_UE_data_recv_189;
extern App_queue Queue_UE_data_recv_190;
extern App_queue Queue_UE_data_recv_191;
extern App_queue Queue_UE_data_recv_192;
extern App_queue Queue_UE_data_recv_193;
extern App_queue Queue_UE_data_recv_194;
extern App_queue Queue_UE_data_recv_195;
extern App_queue Queue_UE_data_recv_196;
extern App_queue Queue_UE_data_recv_197;
extern App_queue Queue_UE_data_recv_198;
extern App_queue Queue_UE_data_recv_199;
extern App_queue Queue_UE_data_recv_200;
extern App_queue Queue_UE_data_recv_201;
extern App_queue Queue_UE_data_recv_202;
extern App_queue Queue_UE_data_recv_203;
extern App_queue Queue_UE_data_recv_204;
extern App_queue Queue_UE_data_recv_205;
extern App_queue Queue_UE_data_recv_206;
extern App_queue Queue_UE_data_recv_207;
extern App_queue Queue_UE_data_recv_208;
extern App_queue Queue_UE_data_recv_209;
extern App_queue Queue_UE_data_recv_210;
extern App_queue Queue_UE_data_recv_211;
extern App_queue Queue_UE_data_recv_212;
extern App_queue Queue_UE_data_recv_213;
extern App_queue Queue_UE_data_recv_214;
extern App_queue Queue_UE_data_recv_215;
extern App_queue Queue_UE_data_recv_216;
extern App_queue Queue_UE_data_recv_217;
extern App_queue Queue_UE_data_recv_218;
extern App_queue Queue_UE_data_recv_219;
extern App_queue Queue_UE_data_recv_220;
extern App_queue Queue_UE_data_recv_221;
extern App_queue Queue_UE_data_recv_222;
extern App_queue Queue_UE_data_recv_223;
extern App_queue Queue_UE_data_recv_224;
extern App_queue Queue_UE_data_recv_225;
extern App_queue Queue_UE_data_recv_226;
extern App_queue Queue_UE_data_recv_227;
extern App_queue Queue_UE_data_recv_228;
extern App_queue Queue_UE_data_recv_229;
extern App_queue Queue_UE_data_recv_230;
extern App_queue Queue_UE_data_recv_231;
extern App_queue Queue_UE_data_recv_232;
extern App_queue Queue_UE_data_recv_233;
extern App_queue Queue_UE_data_recv_234;
extern App_queue Queue_UE_data_recv_235;
extern App_queue Queue_UE_data_recv_236;
extern App_queue Queue_UE_data_recv_237;
extern App_queue Queue_UE_data_recv_238;
extern App_queue Queue_UE_data_recv_239;
extern App_queue Queue_UE_data_recv_240;
extern App_queue Queue_UE_data_recv_241;
extern App_queue Queue_UE_data_recv_242;
extern App_queue Queue_UE_data_recv_243;
extern App_queue Queue_UE_data_recv_244;
extern App_queue Queue_UE_data_recv_245;
extern App_queue Queue_UE_data_recv_246;
extern App_queue Queue_UE_data_recv_247;
extern App_queue Queue_UE_data_recv_248;
extern App_queue Queue_UE_data_recv_249;

/*皇甫阳阳*/
extern App_queue Queue_DL_DATA_Buffer_000;
extern App_queue Queue_DL_DATA_Buffer_001;
extern App_queue Queue_DL_DATA_Buffer_002;
extern App_queue Queue_DL_DATA_Buffer_003;
extern App_queue Queue_DL_DATA_Buffer_004;
extern App_queue Queue_DL_DATA_Buffer_005;
extern App_queue Queue_DL_DATA_Buffer_006;
extern App_queue Queue_DL_DATA_Buffer_007;
extern App_queue Queue_DL_DATA_Buffer_008;
extern App_queue Queue_DL_DATA_Buffer_009;
extern App_queue Queue_DL_DATA_Buffer_010;
extern App_queue Queue_DL_DATA_Buffer_011;
extern App_queue Queue_DL_DATA_Buffer_012;
extern App_queue Queue_DL_DATA_Buffer_013;
extern App_queue Queue_DL_DATA_Buffer_014;
extern App_queue Queue_DL_DATA_Buffer_015;
extern App_queue Queue_DL_DATA_Buffer_016;
extern App_queue Queue_DL_DATA_Buffer_017;
extern App_queue Queue_DL_DATA_Buffer_018;
extern App_queue Queue_DL_DATA_Buffer_019;
extern App_queue Queue_DL_DATA_Buffer_020;
extern App_queue Queue_DL_DATA_Buffer_021;
extern App_queue Queue_DL_DATA_Buffer_022;
extern App_queue Queue_DL_DATA_Buffer_023;
extern App_queue Queue_DL_DATA_Buffer_024;
extern App_queue Queue_DL_DATA_Buffer_025;
extern App_queue Queue_DL_DATA_Buffer_026;
extern App_queue Queue_DL_DATA_Buffer_027;
extern App_queue Queue_DL_DATA_Buffer_028;
extern App_queue Queue_DL_DATA_Buffer_029;
extern App_queue Queue_DL_DATA_Buffer_030;
extern App_queue Queue_DL_DATA_Buffer_031;
extern App_queue Queue_DL_DATA_Buffer_032;
extern App_queue Queue_DL_DATA_Buffer_033;
extern App_queue Queue_DL_DATA_Buffer_034;
extern App_queue Queue_DL_DATA_Buffer_035;
extern App_queue Queue_DL_DATA_Buffer_036;
extern App_queue Queue_DL_DATA_Buffer_037;
extern App_queue Queue_DL_DATA_Buffer_038;
extern App_queue Queue_DL_DATA_Buffer_039;
extern App_queue Queue_DL_DATA_Buffer_040;
extern App_queue Queue_DL_DATA_Buffer_041;
extern App_queue Queue_DL_DATA_Buffer_042;
extern App_queue Queue_DL_DATA_Buffer_043;
extern App_queue Queue_DL_DATA_Buffer_044;
extern App_queue Queue_DL_DATA_Buffer_045;
extern App_queue Queue_DL_DATA_Buffer_046;
extern App_queue Queue_DL_DATA_Buffer_047;
extern App_queue Queue_DL_DATA_Buffer_048;
extern App_queue Queue_DL_DATA_Buffer_049;
extern App_queue Queue_DL_DATA_Buffer_050;
extern App_queue Queue_DL_DATA_Buffer_051;
extern App_queue Queue_DL_DATA_Buffer_052;
extern App_queue Queue_DL_DATA_Buffer_053;
extern App_queue Queue_DL_DATA_Buffer_054;
extern App_queue Queue_DL_DATA_Buffer_055;
extern App_queue Queue_DL_DATA_Buffer_056;
extern App_queue Queue_DL_DATA_Buffer_057;
extern App_queue Queue_DL_DATA_Buffer_058;
extern App_queue Queue_DL_DATA_Buffer_059;
extern App_queue Queue_DL_DATA_Buffer_060;
extern App_queue Queue_DL_DATA_Buffer_061;
extern App_queue Queue_DL_DATA_Buffer_062;
extern App_queue Queue_DL_DATA_Buffer_063;
extern App_queue Queue_DL_DATA_Buffer_064;
extern App_queue Queue_DL_DATA_Buffer_065;
extern App_queue Queue_DL_DATA_Buffer_066;
extern App_queue Queue_DL_DATA_Buffer_067;
extern App_queue Queue_DL_DATA_Buffer_068;
extern App_queue Queue_DL_DATA_Buffer_069;
extern App_queue Queue_DL_DATA_Buffer_070;
extern App_queue Queue_DL_DATA_Buffer_071;
extern App_queue Queue_DL_DATA_Buffer_072;
extern App_queue Queue_DL_DATA_Buffer_073;
extern App_queue Queue_DL_DATA_Buffer_074;
extern App_queue Queue_DL_DATA_Buffer_075;
extern App_queue Queue_DL_DATA_Buffer_076;
extern App_queue Queue_DL_DATA_Buffer_077;
extern App_queue Queue_DL_DATA_Buffer_078;
extern App_queue Queue_DL_DATA_Buffer_079;
extern App_queue Queue_DL_DATA_Buffer_080;
extern App_queue Queue_DL_DATA_Buffer_081;
extern App_queue Queue_DL_DATA_Buffer_082;
extern App_queue Queue_DL_DATA_Buffer_083;
extern App_queue Queue_DL_DATA_Buffer_084;
extern App_queue Queue_DL_DATA_Buffer_085;
extern App_queue Queue_DL_DATA_Buffer_086;
extern App_queue Queue_DL_DATA_Buffer_087;
extern App_queue Queue_DL_DATA_Buffer_088;
extern App_queue Queue_DL_DATA_Buffer_089;
extern App_queue Queue_DL_DATA_Buffer_090;
extern App_queue Queue_DL_DATA_Buffer_091;
extern App_queue Queue_DL_DATA_Buffer_092;
extern App_queue Queue_DL_DATA_Buffer_093;
extern App_queue Queue_DL_DATA_Buffer_094;
extern App_queue Queue_DL_DATA_Buffer_095;
extern App_queue Queue_DL_DATA_Buffer_096;
extern App_queue Queue_DL_DATA_Buffer_097;
extern App_queue Queue_DL_DATA_Buffer_098;
extern App_queue Queue_DL_DATA_Buffer_099;
extern App_queue Queue_DL_DATA_Buffer_100;
extern App_queue Queue_DL_DATA_Buffer_101;
extern App_queue Queue_DL_DATA_Buffer_102;
extern App_queue Queue_DL_DATA_Buffer_103;
extern App_queue Queue_DL_DATA_Buffer_104;
extern App_queue Queue_DL_DATA_Buffer_105;
extern App_queue Queue_DL_DATA_Buffer_106;
extern App_queue Queue_DL_DATA_Buffer_107;
extern App_queue Queue_DL_DATA_Buffer_108;
extern App_queue Queue_DL_DATA_Buffer_109;
extern App_queue Queue_DL_DATA_Buffer_110;
extern App_queue Queue_DL_DATA_Buffer_111;
extern App_queue Queue_DL_DATA_Buffer_112;
extern App_queue Queue_DL_DATA_Buffer_113;
extern App_queue Queue_DL_DATA_Buffer_114;
extern App_queue Queue_DL_DATA_Buffer_115;
extern App_queue Queue_DL_DATA_Buffer_116;
extern App_queue Queue_DL_DATA_Buffer_117;
extern App_queue Queue_DL_DATA_Buffer_118;
extern App_queue Queue_DL_DATA_Buffer_119;
extern App_queue Queue_DL_DATA_Buffer_120;
extern App_queue Queue_DL_DATA_Buffer_121;
extern App_queue Queue_DL_DATA_Buffer_122;
extern App_queue Queue_DL_DATA_Buffer_123;
extern App_queue Queue_DL_DATA_Buffer_124;
extern App_queue Queue_DL_DATA_Buffer_125;
extern App_queue Queue_DL_DATA_Buffer_126;
extern App_queue Queue_DL_DATA_Buffer_127;
extern App_queue Queue_DL_DATA_Buffer_128;
extern App_queue Queue_DL_DATA_Buffer_129;
extern App_queue Queue_DL_DATA_Buffer_130;
extern App_queue Queue_DL_DATA_Buffer_131;
extern App_queue Queue_DL_DATA_Buffer_132;
extern App_queue Queue_DL_DATA_Buffer_133;
extern App_queue Queue_DL_DATA_Buffer_134;
extern App_queue Queue_DL_DATA_Buffer_135;
extern App_queue Queue_DL_DATA_Buffer_136;
extern App_queue Queue_DL_DATA_Buffer_137;
extern App_queue Queue_DL_DATA_Buffer_138;
extern App_queue Queue_DL_DATA_Buffer_139;
extern App_queue Queue_DL_DATA_Buffer_140;
extern App_queue Queue_DL_DATA_Buffer_141;
extern App_queue Queue_DL_DATA_Buffer_142;
extern App_queue Queue_DL_DATA_Buffer_143;
extern App_queue Queue_DL_DATA_Buffer_144;
extern App_queue Queue_DL_DATA_Buffer_145;
extern App_queue Queue_DL_DATA_Buffer_146;
extern App_queue Queue_DL_DATA_Buffer_147;
extern App_queue Queue_DL_DATA_Buffer_148;
extern App_queue Queue_DL_DATA_Buffer_149;
extern App_queue Queue_DL_DATA_Buffer_150;
extern App_queue Queue_DL_DATA_Buffer_151;
extern App_queue Queue_DL_DATA_Buffer_152;
extern App_queue Queue_DL_DATA_Buffer_153;
extern App_queue Queue_DL_DATA_Buffer_154;
extern App_queue Queue_DL_DATA_Buffer_155;
extern App_queue Queue_DL_DATA_Buffer_156;
extern App_queue Queue_DL_DATA_Buffer_157;
extern App_queue Queue_DL_DATA_Buffer_158;
extern App_queue Queue_DL_DATA_Buffer_159;
extern App_queue Queue_DL_DATA_Buffer_160;
extern App_queue Queue_DL_DATA_Buffer_161;
extern App_queue Queue_DL_DATA_Buffer_162;
extern App_queue Queue_DL_DATA_Buffer_163;
extern App_queue Queue_DL_DATA_Buffer_164;
extern App_queue Queue_DL_DATA_Buffer_165;
extern App_queue Queue_DL_DATA_Buffer_166;
extern App_queue Queue_DL_DATA_Buffer_167;
extern App_queue Queue_DL_DATA_Buffer_168;
extern App_queue Queue_DL_DATA_Buffer_169;
extern App_queue Queue_DL_DATA_Buffer_170;
extern App_queue Queue_DL_DATA_Buffer_171;
extern App_queue Queue_DL_DATA_Buffer_172;
extern App_queue Queue_DL_DATA_Buffer_173;
extern App_queue Queue_DL_DATA_Buffer_174;
extern App_queue Queue_DL_DATA_Buffer_175;
extern App_queue Queue_DL_DATA_Buffer_176;
extern App_queue Queue_DL_DATA_Buffer_177;
extern App_queue Queue_DL_DATA_Buffer_178;
extern App_queue Queue_DL_DATA_Buffer_179;
extern App_queue Queue_DL_DATA_Buffer_180;
extern App_queue Queue_DL_DATA_Buffer_181;
extern App_queue Queue_DL_DATA_Buffer_182;
extern App_queue Queue_DL_DATA_Buffer_183;
extern App_queue Queue_DL_DATA_Buffer_184;
extern App_queue Queue_DL_DATA_Buffer_185;
extern App_queue Queue_DL_DATA_Buffer_186;
extern App_queue Queue_DL_DATA_Buffer_187;
extern App_queue Queue_DL_DATA_Buffer_188;
extern App_queue Queue_DL_DATA_Buffer_189;
extern App_queue Queue_DL_DATA_Buffer_190;
extern App_queue Queue_DL_DATA_Buffer_191;
extern App_queue Queue_DL_DATA_Buffer_192;
extern App_queue Queue_DL_DATA_Buffer_193;
extern App_queue Queue_DL_DATA_Buffer_194;
extern App_queue Queue_DL_DATA_Buffer_195;
extern App_queue Queue_DL_DATA_Buffer_196;
extern App_queue Queue_DL_DATA_Buffer_197;
extern App_queue Queue_DL_DATA_Buffer_198;
extern App_queue Queue_DL_DATA_Buffer_199;
extern App_queue Queue_DL_DATA_Buffer_200;
extern App_queue Queue_DL_DATA_Buffer_201;
extern App_queue Queue_DL_DATA_Buffer_202;
extern App_queue Queue_DL_DATA_Buffer_203;
extern App_queue Queue_DL_DATA_Buffer_204;
extern App_queue Queue_DL_DATA_Buffer_205;
extern App_queue Queue_DL_DATA_Buffer_206;
extern App_queue Queue_DL_DATA_Buffer_207;
extern App_queue Queue_DL_DATA_Buffer_208;
extern App_queue Queue_DL_DATA_Buffer_209;
extern App_queue Queue_DL_DATA_Buffer_210;
extern App_queue Queue_DL_DATA_Buffer_211;
extern App_queue Queue_DL_DATA_Buffer_212;
extern App_queue Queue_DL_DATA_Buffer_213;
extern App_queue Queue_DL_DATA_Buffer_214;
extern App_queue Queue_DL_DATA_Buffer_215;
extern App_queue Queue_DL_DATA_Buffer_216;
extern App_queue Queue_DL_DATA_Buffer_217;
extern App_queue Queue_DL_DATA_Buffer_218;
extern App_queue Queue_DL_DATA_Buffer_219;
extern App_queue Queue_DL_DATA_Buffer_220;
extern App_queue Queue_DL_DATA_Buffer_221;
extern App_queue Queue_DL_DATA_Buffer_222;
extern App_queue Queue_DL_DATA_Buffer_223;
extern App_queue Queue_DL_DATA_Buffer_224;
extern App_queue Queue_DL_DATA_Buffer_225;
extern App_queue Queue_DL_DATA_Buffer_226;
extern App_queue Queue_DL_DATA_Buffer_227;
extern App_queue Queue_DL_DATA_Buffer_228;
extern App_queue Queue_DL_DATA_Buffer_229;
extern App_queue Queue_DL_DATA_Buffer_230;
extern App_queue Queue_DL_DATA_Buffer_231;
extern App_queue Queue_DL_DATA_Buffer_232;
extern App_queue Queue_DL_DATA_Buffer_233;
extern App_queue Queue_DL_DATA_Buffer_234;
extern App_queue Queue_DL_DATA_Buffer_235;
extern App_queue Queue_DL_DATA_Buffer_236;
extern App_queue Queue_DL_DATA_Buffer_237;
extern App_queue Queue_DL_DATA_Buffer_238;
extern App_queue Queue_DL_DATA_Buffer_239;
extern App_queue Queue_DL_DATA_Buffer_240;
extern App_queue Queue_DL_DATA_Buffer_241;
extern App_queue Queue_DL_DATA_Buffer_242;
extern App_queue Queue_DL_DATA_Buffer_243;
extern App_queue Queue_DL_DATA_Buffer_244;
extern App_queue Queue_DL_DATA_Buffer_245;
extern App_queue Queue_DL_DATA_Buffer_246;
extern App_queue Queue_DL_DATA_Buffer_247;
extern App_queue Queue_DL_DATA_Buffer_248;
extern App_queue Queue_DL_DATA_Buffer_249;

// 缓存RLC传下来的业务包的vector
extern cvector DL_data_buffer_Cvector_000;
extern cvector DL_data_buffer_Cvector_001;
extern cvector DL_data_buffer_Cvector_002;
extern cvector DL_data_buffer_Cvector_003;
extern cvector DL_data_buffer_Cvector_004;
extern cvector DL_data_buffer_Cvector_005;
extern cvector DL_data_buffer_Cvector_006;
extern cvector DL_data_buffer_Cvector_007;
extern cvector DL_data_buffer_Cvector_008;
extern cvector DL_data_buffer_Cvector_009;
extern cvector DL_data_buffer_Cvector_010;
extern cvector DL_data_buffer_Cvector_011;
extern cvector DL_data_buffer_Cvector_012;
extern cvector DL_data_buffer_Cvector_013;
extern cvector DL_data_buffer_Cvector_014;
extern cvector DL_data_buffer_Cvector_015;
extern cvector DL_data_buffer_Cvector_016;
extern cvector DL_data_buffer_Cvector_017;
extern cvector DL_data_buffer_Cvector_018;
extern cvector DL_data_buffer_Cvector_019;
extern cvector DL_data_buffer_Cvector_020;
extern cvector DL_data_buffer_Cvector_021;
extern cvector DL_data_buffer_Cvector_022;
extern cvector DL_data_buffer_Cvector_023;
extern cvector DL_data_buffer_Cvector_024;
extern cvector DL_data_buffer_Cvector_025;
extern cvector DL_data_buffer_Cvector_026;
extern cvector DL_data_buffer_Cvector_027;
extern cvector DL_data_buffer_Cvector_028;
extern cvector DL_data_buffer_Cvector_029;
extern cvector DL_data_buffer_Cvector_030;
extern cvector DL_data_buffer_Cvector_031;
extern cvector DL_data_buffer_Cvector_032;
extern cvector DL_data_buffer_Cvector_033;
extern cvector DL_data_buffer_Cvector_034;
extern cvector DL_data_buffer_Cvector_035;
extern cvector DL_data_buffer_Cvector_036;
extern cvector DL_data_buffer_Cvector_037;
extern cvector DL_data_buffer_Cvector_038;
extern cvector DL_data_buffer_Cvector_039;
extern cvector DL_data_buffer_Cvector_040;
extern cvector DL_data_buffer_Cvector_041;
extern cvector DL_data_buffer_Cvector_042;
extern cvector DL_data_buffer_Cvector_043;
extern cvector DL_data_buffer_Cvector_044;
extern cvector DL_data_buffer_Cvector_045;
extern cvector DL_data_buffer_Cvector_046;
extern cvector DL_data_buffer_Cvector_047;
extern cvector DL_data_buffer_Cvector_048;
extern cvector DL_data_buffer_Cvector_049;
extern cvector DL_data_buffer_Cvector_050;
extern cvector DL_data_buffer_Cvector_051;
extern cvector DL_data_buffer_Cvector_052;
extern cvector DL_data_buffer_Cvector_053;
extern cvector DL_data_buffer_Cvector_054;
extern cvector DL_data_buffer_Cvector_055;
extern cvector DL_data_buffer_Cvector_056;
extern cvector DL_data_buffer_Cvector_057;
extern cvector DL_data_buffer_Cvector_058;
extern cvector DL_data_buffer_Cvector_059;
extern cvector DL_data_buffer_Cvector_060;
extern cvector DL_data_buffer_Cvector_061;
extern cvector DL_data_buffer_Cvector_062;
extern cvector DL_data_buffer_Cvector_063;
extern cvector DL_data_buffer_Cvector_064;
extern cvector DL_data_buffer_Cvector_065;
extern cvector DL_data_buffer_Cvector_066;
extern cvector DL_data_buffer_Cvector_067;
extern cvector DL_data_buffer_Cvector_068;
extern cvector DL_data_buffer_Cvector_069;
extern cvector DL_data_buffer_Cvector_070;
extern cvector DL_data_buffer_Cvector_071;
extern cvector DL_data_buffer_Cvector_072;
extern cvector DL_data_buffer_Cvector_073;
extern cvector DL_data_buffer_Cvector_074;
extern cvector DL_data_buffer_Cvector_075;
extern cvector DL_data_buffer_Cvector_076;
extern cvector DL_data_buffer_Cvector_077;
extern cvector DL_data_buffer_Cvector_078;
extern cvector DL_data_buffer_Cvector_079;
extern cvector DL_data_buffer_Cvector_080;
extern cvector DL_data_buffer_Cvector_081;
extern cvector DL_data_buffer_Cvector_082;
extern cvector DL_data_buffer_Cvector_083;
extern cvector DL_data_buffer_Cvector_084;
extern cvector DL_data_buffer_Cvector_085;
extern cvector DL_data_buffer_Cvector_086;
extern cvector DL_data_buffer_Cvector_087;
extern cvector DL_data_buffer_Cvector_088;
extern cvector DL_data_buffer_Cvector_089;
extern cvector DL_data_buffer_Cvector_090;
extern cvector DL_data_buffer_Cvector_091;
extern cvector DL_data_buffer_Cvector_092;
extern cvector DL_data_buffer_Cvector_093;
extern cvector DL_data_buffer_Cvector_094;
extern cvector DL_data_buffer_Cvector_095;
extern cvector DL_data_buffer_Cvector_096;
extern cvector DL_data_buffer_Cvector_097;
extern cvector DL_data_buffer_Cvector_098;
extern cvector DL_data_buffer_Cvector_099;
extern cvector DL_data_buffer_Cvector_100;
extern cvector DL_data_buffer_Cvector_101;
extern cvector DL_data_buffer_Cvector_102;
extern cvector DL_data_buffer_Cvector_103;
extern cvector DL_data_buffer_Cvector_104;
extern cvector DL_data_buffer_Cvector_105;
extern cvector DL_data_buffer_Cvector_106;
extern cvector DL_data_buffer_Cvector_107;
extern cvector DL_data_buffer_Cvector_108;
extern cvector DL_data_buffer_Cvector_109;
extern cvector DL_data_buffer_Cvector_110;
extern cvector DL_data_buffer_Cvector_111;
extern cvector DL_data_buffer_Cvector_112;
extern cvector DL_data_buffer_Cvector_113;
extern cvector DL_data_buffer_Cvector_114;
extern cvector DL_data_buffer_Cvector_115;
extern cvector DL_data_buffer_Cvector_116;
extern cvector DL_data_buffer_Cvector_117;
extern cvector DL_data_buffer_Cvector_118;
extern cvector DL_data_buffer_Cvector_119;
extern cvector DL_data_buffer_Cvector_120;
extern cvector DL_data_buffer_Cvector_121;
extern cvector DL_data_buffer_Cvector_122;
extern cvector DL_data_buffer_Cvector_123;
extern cvector DL_data_buffer_Cvector_124;
extern cvector DL_data_buffer_Cvector_125;
extern cvector DL_data_buffer_Cvector_126;
extern cvector DL_data_buffer_Cvector_127;
extern cvector DL_data_buffer_Cvector_128;
extern cvector DL_data_buffer_Cvector_129;
extern cvector DL_data_buffer_Cvector_130;
extern cvector DL_data_buffer_Cvector_131;
extern cvector DL_data_buffer_Cvector_132;
extern cvector DL_data_buffer_Cvector_133;
extern cvector DL_data_buffer_Cvector_134;
extern cvector DL_data_buffer_Cvector_135;
extern cvector DL_data_buffer_Cvector_136;
extern cvector DL_data_buffer_Cvector_137;
extern cvector DL_data_buffer_Cvector_138;
extern cvector DL_data_buffer_Cvector_139;
extern cvector DL_data_buffer_Cvector_140;
extern cvector DL_data_buffer_Cvector_141;
extern cvector DL_data_buffer_Cvector_142;
extern cvector DL_data_buffer_Cvector_143;
extern cvector DL_data_buffer_Cvector_144;
extern cvector DL_data_buffer_Cvector_145;
extern cvector DL_data_buffer_Cvector_146;
extern cvector DL_data_buffer_Cvector_147;
extern cvector DL_data_buffer_Cvector_148;
extern cvector DL_data_buffer_Cvector_149;
extern cvector DL_data_buffer_Cvector_150;
extern cvector DL_data_buffer_Cvector_151;
extern cvector DL_data_buffer_Cvector_152;
extern cvector DL_data_buffer_Cvector_153;
extern cvector DL_data_buffer_Cvector_154;
extern cvector DL_data_buffer_Cvector_155;
extern cvector DL_data_buffer_Cvector_156;
extern cvector DL_data_buffer_Cvector_157;
extern cvector DL_data_buffer_Cvector_158;
extern cvector DL_data_buffer_Cvector_159;
extern cvector DL_data_buffer_Cvector_160;
extern cvector DL_data_buffer_Cvector_161;
extern cvector DL_data_buffer_Cvector_162;
extern cvector DL_data_buffer_Cvector_163;
extern cvector DL_data_buffer_Cvector_164;
extern cvector DL_data_buffer_Cvector_165;
extern cvector DL_data_buffer_Cvector_166;
extern cvector DL_data_buffer_Cvector_167;
extern cvector DL_data_buffer_Cvector_168;
extern cvector DL_data_buffer_Cvector_169;
extern cvector DL_data_buffer_Cvector_170;
extern cvector DL_data_buffer_Cvector_171;
extern cvector DL_data_buffer_Cvector_172;
extern cvector DL_data_buffer_Cvector_173;
extern cvector DL_data_buffer_Cvector_174;
extern cvector DL_data_buffer_Cvector_175;
extern cvector DL_data_buffer_Cvector_176;
extern cvector DL_data_buffer_Cvector_177;
extern cvector DL_data_buffer_Cvector_178;
extern cvector DL_data_buffer_Cvector_179;
extern cvector DL_data_buffer_Cvector_180;
extern cvector DL_data_buffer_Cvector_181;
extern cvector DL_data_buffer_Cvector_182;
extern cvector DL_data_buffer_Cvector_183;
extern cvector DL_data_buffer_Cvector_184;
extern cvector DL_data_buffer_Cvector_185;
extern cvector DL_data_buffer_Cvector_186;
extern cvector DL_data_buffer_Cvector_187;
extern cvector DL_data_buffer_Cvector_188;
extern cvector DL_data_buffer_Cvector_189;
extern cvector DL_data_buffer_Cvector_190;
extern cvector DL_data_buffer_Cvector_191;
extern cvector DL_data_buffer_Cvector_192;
extern cvector DL_data_buffer_Cvector_193;
extern cvector DL_data_buffer_Cvector_194;
extern cvector DL_data_buffer_Cvector_195;
extern cvector DL_data_buffer_Cvector_196;
extern cvector DL_data_buffer_Cvector_197;
extern cvector DL_data_buffer_Cvector_198;
extern cvector DL_data_buffer_Cvector_199;
extern cvector DL_data_buffer_Cvector_200;
extern cvector DL_data_buffer_Cvector_201;
extern cvector DL_data_buffer_Cvector_202;
extern cvector DL_data_buffer_Cvector_203;
extern cvector DL_data_buffer_Cvector_204;
extern cvector DL_data_buffer_Cvector_205;
extern cvector DL_data_buffer_Cvector_206;
extern cvector DL_data_buffer_Cvector_207;
extern cvector DL_data_buffer_Cvector_208;
extern cvector DL_data_buffer_Cvector_209;
extern cvector DL_data_buffer_Cvector_210;
extern cvector DL_data_buffer_Cvector_211;
extern cvector DL_data_buffer_Cvector_212;
extern cvector DL_data_buffer_Cvector_213;
extern cvector DL_data_buffer_Cvector_214;
extern cvector DL_data_buffer_Cvector_215;
extern cvector DL_data_buffer_Cvector_216;
extern cvector DL_data_buffer_Cvector_217;
extern cvector DL_data_buffer_Cvector_218;
extern cvector DL_data_buffer_Cvector_219;
extern cvector DL_data_buffer_Cvector_220;
extern cvector DL_data_buffer_Cvector_221;
extern cvector DL_data_buffer_Cvector_222;
extern cvector DL_data_buffer_Cvector_223;
extern cvector DL_data_buffer_Cvector_224;
extern cvector DL_data_buffer_Cvector_225;
extern cvector DL_data_buffer_Cvector_226;
extern cvector DL_data_buffer_Cvector_227;
extern cvector DL_data_buffer_Cvector_228;
extern cvector DL_data_buffer_Cvector_229;
extern cvector DL_data_buffer_Cvector_230;
extern cvector DL_data_buffer_Cvector_231;
extern cvector DL_data_buffer_Cvector_232;
extern cvector DL_data_buffer_Cvector_233;
extern cvector DL_data_buffer_Cvector_234;
extern cvector DL_data_buffer_Cvector_235;
extern cvector DL_data_buffer_Cvector_236;
extern cvector DL_data_buffer_Cvector_237;
extern cvector DL_data_buffer_Cvector_238;
extern cvector DL_data_buffer_Cvector_239;
extern cvector DL_data_buffer_Cvector_240;
extern cvector DL_data_buffer_Cvector_241;
extern cvector DL_data_buffer_Cvector_242;
extern cvector DL_data_buffer_Cvector_243;
extern cvector DL_data_buffer_Cvector_244;
extern cvector DL_data_buffer_Cvector_245;
extern cvector DL_data_buffer_Cvector_246;
extern cvector DL_data_buffer_Cvector_247;
extern cvector DL_data_buffer_Cvector_248;
extern cvector DL_data_buffer_Cvector_249;

// Mac-PHY 发射端组发往物理层的控制信息用的缓存队列
extern App_queue Queue_DL_CCH_DATA_Packaging_Buffer;
// Mac-PHY 发射端组发往物理层的业务信息用的缓存队列
extern App_queue Queue_DL_SCH_DATA_Packaging_Buffer;

typedef struct
{
    u16 slot0_uplink_en;
    u16 slot0_downlink_en;
} CCH_RB_SlotIndex;

typedef struct
{
    // 记录的是上下行控制信道的RB_begin
    u16 slot0_uplink_FrequencyPoint;
    u16 slot0_downlink_FrequencyPoint;
} CCH_RB_FrequencyPoint;

typedef struct
{
    u16 slot1_uplink_en;
    u16 slot2_uplink_en;
    u16 slot3_uplink_en;
    u16 slot1_downlink_en;
    u16 slot2_downlink_en;
    u16 slot3_downlink_en;
} SCH_RB_SlotIndex;

typedef struct
{
    u16 slot1_uplink_FrequencyPoint[SCH_RB_FREQ_POINT_ARRAY_SIZE];
    u16 slot2_uplink_FrequencyPoint[SCH_RB_FREQ_POINT_ARRAY_SIZE];
    u16 slot3_uplink_FrequencyPoint[SCH_RB_FREQ_POINT_ARRAY_SIZE];
    u16 slot1_downlink_FrequencyPoint[SCH_RB_FREQ_POINT_ARRAY_SIZE];
    u16 slot2_downlink_FrequencyPoint[SCH_RB_FREQ_POINT_ARRAY_SIZE];
    u16 slot3_downlink_FrequencyPoint[SCH_RB_FREQ_POINT_ARRAY_SIZE];
} SCH_RB_FrequencyPoint;

typedef struct
{
    u16 slot1_uplink_FrequencyPoint_AllotNum;
    u16 slot2_uplink_FrequencyPoint_AllotNum;
    u16 slot3_uplink_FrequencyPoint_AllotNum;
    u16 slot1_downlink_FrequencyPoint_AllotNum;
    u16 slot2_downlink_FrequencyPoint_AllotNum;
    u16 slot3_downlink_FrequencyPoint_AllotNum;
} SCH_RB_FrequencyPoint_AllotNum;

// 用户注册信息
typedef struct
{
    u8 id;              // UE标识
    u8 isAccessGranted; // 是否获得随机接入许可
    u8 accessAttempt;   // 随机接入尝试次数
    u16 state;
    u32 U_RNTI;
    u48 UE_MAC_addr;
    u16 BeamIndex;
    u16 BeamPositionIndex;
    u16 wave_user_index; // 记录用户在记录虚波位接入的用户数量的数组的第二个维度的索引
    u32 UL_MCS;          // 记录上行业务信道调制方式
    u32 DL_MCS;          // 记录下行业务信道调制方式
    u32 IPv4;            // 用户的IPV4
    CCH_RB_SlotIndex CCH_SlotIndex;
    CCH_RB_FrequencyPoint CCH_FrequencyPoint;

    // 业务资源信息，用于生成SCH_FILE通知用户为其分配的业务信道资源
    // 本次为用户分配的上行SCH_RB，将会在下一次波束对上时收到
    u16 UL_SCH_RB_begin;
    u16 UL_SCH_RB_Total_NUM;
    // 上一次次为用户分配的上行SCH_RB，将会在本次波束对上时收到
    u16 eatrly_UL_SCH_RB_begin;
    u16 eatrly_UL_SCH_RB_Total_NUM;
    // 分配的下行业务资源，下行业务会直接在分配后发下
    u16 DL_SCH_RB_begin;
    u16 DL_SCH_RB_Total_NUM;

    SCH_RB_SlotIndex SCH_SlotIndex;
    SCH_RB_FrequencyPoint SCH_FrequencyPoint;
    SCH_RB_FrequencyPoint_AllotNum SCH_FrequencyPoint_AllotNum;
} UserInfo;

/*控制资源空闲RB数量*/
typedef struct
{
    u16 ulcch_rb_idlenum; // 上行控制信道剩余空闲资源数
    u16 dlcch_rb_idlenum; // 下行控制信道剩余空闲资源数
} CCH_RB_idlenum;

/*业务信道RB空闲数记录结构体*/
typedef struct
{
    u16 ulsch_rb_idlenum; // 上行业务信道剩余空闲资源数
    u16 dlsch_rb_idlenum; // 下行业务信道剩余空闲资源数
} SCH_RB_idlenum;

/*下行业务各个时隙被占用的RB数量*/
typedef struct
{
    u16 dlsch_slt1_rbnum;
    u16 dlsch_slt2_rbnum;
    u16 dlsch_slt3_rbnum;
} SCH_RB_occupiednum;

/*虚波位调度最小单元：用户信息块*/
// typedef struct
// {
//     u8 State;
//     u32 U_RNTI;
//     u8 UE_Level;
//     u32 MCS;
//     cvector *User_DataQueue_ptr;

//     // [MLRA] 新增动态调度参数
//     double Dynamic_Priority; // 计算出的综合优先级 k_j
//     u32 Avg_Data_Rate;       // R_j: 平均传输速率 (用于 PF 比例公平计算)
//     u32 Head_Of_Line_Delay;  // W_j: 队头数据等待时延 (ms)
//     u8 Is_RealTime;          // 1=RT, 0=nRT (由业务类型决定)
// } UserInfo_Block;
// [MODIFIED] 用户信息块 (User Context in Beam Map)
typedef struct
{
    u8 State;
    u32 U_RNTI;
    
    // [MLRA User-Level Params]
    u8 UE_Level;            // 静态 QoS 等级
    u8 Is_RealTime;         // 1=RT, 0=nRT
    double Dynamic_Priority;// k_j: 计算出的动态优先级
    
    // 速率与历史记录 (对应 MATLAB 中的 R(i))
    double Avg_Data_Rate;   // R_j: 滑动平均速率
    u32 Instant_Rate;       // r_j: 当前瞬间可达速率 (基于 MCS)
    
    // 时延与队列
    u32 Head_Of_Line_Delay; // W_j: 队头包等待时间 (ms)
    u32 Queue_Len;          // q_j: 队列长度 (Bytes)
    
    // 位置与信道
    double Location_Factor; // L_j: 位置因子 (基于距离)
    u32 MCS;                // kappa_j
    
    cvector *User_DataQueue_ptr;
} UserInfo_Block;
/*记录下行资源分配时的CCH信息和SCH信息*/
typedef struct
{
    /*CCH*/
    u8 CCH_RB_begin;

    u16 CCH_frame_head;
    u48 CCH_DEST_MAC;
    u48 CCH_SRC_MAC;
    u16 CCH_Data_Length; // 记录CCH_DATA的有效长度，不包括MAC帧头的16字节
    u8 CCH_DATA[CCH_DATA_LENGTH - MAC_FRAME_LENGTH];

    /*SCH*/
    u8 SCH_MCS;
    u16 SCH_TBS;
    u16 SCH_RB_Begin;
    u16 SCH_RB_Length;

    u16 SCH_frame_head;
    u48 SCH_DEST_MAC;
    u48 SCH_SRC_MAC;
    u16 SCH_Data_Length; // 记录SCH_DATA的有效长度，不包括MAC帧头的16字节
    u8 SCH_data[0];
} Mac_to_PHY;

/*记录接收端MAC->PHY需要传递的信息的结构体*/
typedef struct
{
    u8 CCH_RB_begin;

    u8 SCH_MCS;
    u16 SCH_TBS;
    u16 SCH_RB_Begin;
    u16 SCH_RB_Length;
} Mac_to_PHY_rec;

/*yinjian*/
// 测试代码
typedef struct
{
    u8 userNum;
} userNum_Print_Type;

typedef struct
{
    u8 CCH_TF_Begin;
    u8 DATA[0];
} CCH_Print_Type;

typedef struct
{
    u8 SCH_MCS;
    u16 SCH_TBS;
    u16 SCH_TF_BEGIN;
    u16 SCH_TF_LENGTH;
    u8 DATA[0];
} SCH_Print_Type;
// [NEW] 性能统计结构体
typedef struct {
    // 1. 接入性能
    u32 rach_attempts;          // 总接入尝试次数
    u32 rach_success;           // 接入成功次数
    u32 rach_collisions;        // (仿真) 碰撞/拒绝次数

    // 2. 吞吐量性能 (Bytes)
    u64 total_throughput_bytes; // 总吞吐量
    u64 rt_throughput_bytes;    // 实时业务吞吐量
    u64 nrt_throughput_bytes;   // 非实时业务吞吐量

    // 3. 资源利用率
    u32 total_rb_available;     // 总可用 RB 数 (累加)
    u32 total_rb_used;          // 实际使用 RB 数 (累加)

    // 4. 时延 (简单累加，用于求平均)
    u64 total_packet_delay;     // 累积包时延 (ms)
    u32 total_packets_sent;     // 发包总数

    // 5. 调度公平性辅助
    double sum_avg_rates;       // Σ R_i
    double sum_sq_avg_rates;    // Σ (R_i)^2 (用于计算 Jain's Fairness Index)
} Mac_Perf_Stats;
void get_own_address(char *macNum);
void printCurrentTime();
long getCurrentMicroseconds();
int getCurrentSecond();
void BufferCopy(u8 *DestBuf, u8 *SrcBuf, u16 Datalen);
void BufferClear(u8 *Buf, u16 Datalen);
void Global_queue_init();
int getCurrentMinute();

extern Mac_Perf_Stats g_MacStats;
void Print_Performance_Report(float simulation_time_sec); // 打印报告函数
#endif
